In [75]:
import boto3
import pandas as pd
from collections import Counter
import re

# IndiaNGO
## About this dataset
Data provided by: Shehkar<br>
Source: s3://daanmatchdatafiles/from Shekhar/Final_Data_Indiangoslist_v1.com.xlsx<br>
Type: xlsx<br>
Last June 14, 2021, 21:46:43 (UTC-07:00)<br>
Size: 30.1 MB<br>

In [3]:
client = boto3.client('s3')
resource = boto3.resource('s3')
my_bucket = resource.Bucket('daanmatchdatafiles')

In [4]:
path = "s3://daanmatchdatafiles/from Shekhar/Final_Data_Indiangoslist_v1.com.xlsx"
xl = pd.ExcelFile(path)
print(xl.sheet_names)
Final_Data_IndiaNGO = xl.parse(xl.sheet_names[0])
Final_Data_IndiaNGO.head()

['indiangoslist.com']

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
0,http://www.indiangoslist.com/ngo-address/abo-t...,ABO TANI WELFARE SOCIETY,AR/2010/0027372,Mage Kamda,Mage Kamda,Paksing Maling,Tape Maling,Registrar of Societies,Society,SR/ITA/2271,...,Arunachal Pradesh,0360-2292635,9.436054e+09,"Village Kodak, P.O- and P.S- Taliha, Upper Sub...",atwsngo@yahoo.in,NaN,NaN,ABO TANI WELFARE SOCIETY is located in Upper S...,This ABO TANI WELFARE SOCIETY NGO charity is w...,"Flower Plantation, Weaving Material, Youth Dev..."
1,http://www.indiangoslist.com/ngo-address/aan-a...,AAN AAB WELFARE SOCIETY,AR/2010/0038998,Chairman,Chairman,NaN,NaN,Registrar of Cooperative Societies,Cooperative Society,SR/ITS/3251,...,Arunachal Pradesh,9199-100015,NaN,Tili Lower Subansiri District,aaws2011@gmail.com,NaN,NaN,AAN AAB WELFARE SOCIETY is located in Lower Su...,This AAN AAB WELFARE SOCIETY NGO charity is wo...,Orphanage Home
2,http://www.indiangoslist.com/ngo-address/amik-...,AMIK MATAI SOCIETY,AR/2009/0009702,Rakhi Bora,Ruzing Bellai,Sonem Kri,Dalimi Tayang,Registrar of Societies,Society,SR ITA 2849,...,Arunachal Pradesh,03804-222878,9.436227e+09,Amik Matai Society Post Box No 8 New Mekailian...,amikmatai@gmail.com,http://ngo.india.gov.in,03804-222878,AMIK MATAI SOCIETY is located in Tezu Arunacha...,This AMIK MATAI SOCIETY NGO charity is working...,Implemented the National Bamboo Mission progra...
3,http://www.indiangoslist.com/ngo-address/all-h...,ALL HAMAI DEVELOPMENT ASSOCIATION AHDA,AR/2012/0048621,Shri Tani Singyum,Shri Tani Singyum,NaN,NaN,Registrar of Societies,Society,SR/ITA/8728,...,Arunachal Pradesh,0379-2224167,NaN,Rural works Division Daporijo Upper Subansiri ...,allgumsing@gmail.com,NaN,NaN,ALL HAMAI DEVELOPMENT ASSOCIATION AHDA is loca...,This ALL HAMAI DEVELOPMENT ASSOCIATION AHDA NG...,Rural Development & Poverty Alleviation progra...
4,http://www.indiangoslist.com/ngo-address/ane-a...,ANE ABO WELFARE SOCIETY,AR/2010/0036913,Shri Hengo Bam,Shri Hengo Bam,Mrs Yabi Bam,Shri Henya Bam,Registrar of Societies,Society,SR/ITA/2616,...,Arunachal Pradesh,0379-5222241,9.436411e+09,"Basar, West Siang District Arunachal Pradesh.",aneabow@gmail.com,NaN,NaN,ANE ABO WELFARE SOCIETY is located in Arunacha...,This ANE ABO WELFARE SOCIETY NGO charity is wo...,Maintenance and running of: (1) Treatment cum ...

In [5]:
Final_Data_IndiaNGO.columns

Index(['Url', 'NGO Name', 'Unique Id', 'Chief Functionary', 'Chairman',
       'Secretary', 'Treasurer', 'Registered With', 'Type of NGO',
       'Registration Number', 'City of Registration', 'State of Registration',
       'Date of Registration', 'City', 'State', 'Telephone', 'Mobile',
       'Address', 'email', 'Website', 'Fax', 'Ngo Information', 'Key Issues',
       'Major Activities and Achivements'],
      dtype='object')

In [6]:
dataset = Final_Data_IndiaNGO
print("Shape:", dataset.shape)
print("Rows:", dataset.shape[0])
print("Columns:", dataset.shape[1])
print("Each row is a NGO.")

Shape: (56184, 24)
Rows: 56184
Columns: 24
Each row is a NGO.

In [9]:
dataset_columns = [column for column in dataset.columns]
dataset_desc = ['Url of NGO', 
                'NGO Name', 
                'Unique Id of NGO', 
                'Chief Functionary of NGO', 
                'Chairman of NGO',
                'Secretary of NGO', 
                'Treasurermof NGO', 
                'What did the NGO Register with', 
                'Type of NGO',
                'Registration Number', 
                'City of Registration', 
                'State of Registration',
                'Date of Registration', 
                'City currently in', 
                'State currently in', 
                'Telephone', 
                'Mobile',
                'Address', 
                'email', 
                'Website', 
                'Fax', 
                'Ngo Information', 
                'Key Issues',
                'Major Activities and Achivements'
               ]
dataset_desc = dataset_desc + ["N/A"] * (len(dataset_columns) - len(dataset_desc))
dataset_dtypes = [dtype for dtype in dataset.dtypes]
data = {"Column Name": dataset_columns, "Description": dataset_desc, "Type": dataset_dtypes}
codebook = pd.DataFrame(data)
codebook

,Column Name,Description,Type
0,Url,Url of NGO,object
1,NGO Name,NGO Name,object
2,Unique Id,Unique Id of NGO,object
3,Chief Functionary,Chief Functionary of NGO,object
4,Chairman,Chairman of NGO,object
5,Secretary,Secretary of NGO,object
6,Treasurer,Treasurermof NGO,object
7,Registered With,What did the NGO Register with,object
8,Type of NGO,Type of NGO,object
9,Registration Number,Registration Number,object
10,City of Registration,City of Registration,object
11,State of Registration,State of Registration,object
12,Date of Registration,Date of Registration,object
13,City,City currently in,object
14,State,State currently in,object
15,Telephone,Telephone,object
16,Mobile,Mobile,float64
17,Address,Address,object
18,email,email,object
19,Website,Website,object
20,Fax,Fax,object
21,Ngo Information,Ngo Information,object
22,Key Issues,Key Issues,object
23,Major Activities and Achivements,Major Activities and Achivements,object

In [11]:
Final_Data_IndiaNGO.isnull().sum()

Url                                     0
NGO Name                                3
Unique Id                               0
Chief Functionary                       6
Chairman                              311
Secretary                            6174
Treasurer                            7389
Registered With                         0
Type of NGO                             0
Registration Number                     4
City of Registration                  268
State of Registration                 266
Date of Registration                   36
City                                 2373
State                                   0
Telephone                               0
Mobile                               6599
Address                                37
email                                  35
Website                             44124
Fax                                 44273
Ngo Information                         0
Key Issues                          11178
Major Activities and Achivements      266
dtype: int64

# Name of NGO

In [13]:
column = dataset["NGO Name"]
column

0                                 ABO TANI WELFARE SOCIETY
1                                  AAN AAB WELFARE SOCIETY
2                                       AMIK MATAI SOCIETY
3                   ALL HAMAI DEVELOPMENT ASSOCIATION AHDA
4                                  ANE ABO WELFARE SOCIETY
                               ...
56179    SOCIETY FOR EMPOWERMENT OF VILLAGES AND AGRICU...
56180      SOCIETY FOR INSTITUTE OF INFORMATION TECHNOLOGY
56181    SOCIETY FOR INTEGRATD DEVELOPMENT AND RESEARCH...
56182    SOCIETY FOR NATIONALISM EDUCATION AND HEALTH A...
56183    SOCIETY FOR PROMOTION OF AREA RESOURCE CENTRES...
Name: NGO Name, Length: 56184, dtype: object

In [16]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 3
No. of unique values: 52455
No. of duplicates: 2698

                                        Duplicate Names  Count
0                                                   NGO     43
1                             RURAL DEVELOPMENT SOCIETY     25
2                                 JAN SHIKSHAN SANSTHAN     14
3                                               PRAGATI     14
4                                                PRAYAS     12
...                                                 ...    ...
2693  COUNCIL FOR RURAL TECHNOLOGY AND RESEARCH INST...      2
2694                       NAGEN SARMA MEMORIAL SOCIETY      2
2695                           CONSUMER PROTECTION CELL      2
2696              DEVELOPMEN TACTIONSOC IETYFOUNDA TION      2
2697                ALL INDIA ANTI CORRUPTION COMMITTEE      2

[2698 rows x 2 columns]

In [17]:
dataset[column == table.iloc[0,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
4565,http://www.indiangoslist.com/ngo-address/ngo-i...,NGO,HP/2009/0001543,Education,Vinod Kumar,Ashok Kumar,Vinod Kumar,Registrar of Societies,Society,2213/H,...,Himachal Pradesh,01972-278747,9.817276e+09,VPO Tauni Devi Teh. Distt. Hamirpur (H.P) 177023,siit_edu@yahoo.in,NaN,01972-278747,NGO is located in Hamirpur Himachal Pradesh . ...,This NGO NGO charity is working on Key Issues ...,running a computer centre in which we provide ...
8920,http://www.indiangoslist.com/ngo-address/ngo-i...,NGO,HR/2011/0047384,Chairman,Devender Kumar,Amit Kumar,Virender kumar,Registrar of Societies,Society,S/00191-NE/2011,...,Haryana,0184-2396064,9.416841e+09,"Regional Office:-V.P.O- Badar Pur, Via.- Garhi...",kamboj08@rediffmail.com,NaN,NaN,NGO is located in Karnal Haryana . NGO is regi...,This NGO NGO charity is working on Key Issues ...,"Water Resources, Women Empowerment, Youth , Ch..."
17885,http://www.indiangoslist.com/ngo-address/ngo-i...,NGO,UA/2013/0068576,kailash chandra lohani,kailash chandra lohani,bhuwan garkoti,kanchan kandpal,Registrar of Societies,Society,283HA,...,Uttarkhand,05943-265446,8.006719e+09,rural Environmental And educational developmen...,reedstnp2001@gmail.com,NaN,05943-265446,NGO is located in tanakpur Uttarkhand . NGO is...,This NGO NGO charity is working on Key Issues ...,running all five component of ujjawala in the ...
22645,http://www.indiangoslist.com/ngo-address/ngo-i...,NGO,KA/2009/0022122,MS Bhagya,MS Bhagya,AP Palaiah,G Venkatesh,Sub-Registrar,Society,CDG-S268-2007-08,...,Karnataka,08195-000000,9.740589e+09,PRAGATHI EDUCATION & RURAL DEVELOPMENT SOCIETY...,pragathierds@gmail.com,NaN,NaN,NGO is located in NAYAKANAHATTI Karnataka . NG...,This NGO NGO charity is working on Key Issues ...,SHG FORMATION WATER SHAD DEVELOPMENT HEALTH ED...
22648,http://www.indiangoslist.com/ngo-address/ngo-i...,NGO,KA/2011/0042427,Pesh Imam Educational society,Syed Moinuddin,Zakera Begum,Syed Merajudding,Registrar of Societies,Society,44/2006-07,...,Karnataka,08482-24455,9.945907e+09,"Ranjhol Kheni, Tq & Dist. Bidar - 585401",peshmamsociety@gmail.com,http://www.nog.india.gov.in,NaN,NGO is located in Karnataka . NGO is registere...,This NGO NGO charity is working on Key Issues ...,We are providing a better teaching in our orga...

# URL of NGO

In [19]:
column = dataset["Url"]
column

0        http://www.indiangoslist.com/ngo-address/abo-t...
1        http://www.indiangoslist.com/ngo-address/aan-a...
2        http://www.indiangoslist.com/ngo-address/amik-...
3        http://www.indiangoslist.com/ngo-address/all-h...
4        http://www.indiangoslist.com/ngo-address/ane-a...
                               ...
56179    http://www.indiangoslist.com/ngo-address/socie...
56180    http://www.indiangoslist.com/ngo-address/socie...
56181    http://www.indiangoslist.com/ngo-address/socie...
56182    http://www.indiangoslist.com/ngo-address/socie...
56183    http://www.indiangoslist.com/ngo-address/socie...
Name: Url, Length: 56184, dtype: object

In [20]:
# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))

print("No. of unique values:", len(column.unique()))

# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of Duplicates:", len(duplicates))

table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate URLs", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 0
No. of unique values: 56184
No. of Duplicates: 0

Empty DataFrame
Columns: [Duplicate URLs, Count]
Index: []

In [21]:
table.iloc[13:]

Empty DataFrame
Columns: [Duplicate URLs, Count]
Index: []

In [23]:
#dataset[column == table.iloc[13,0]].head()

# ID of NGO

In [28]:
column = dataset["Unique Id"]
column

0        AR/2010/0027372
1        AR/2010/0038998
2        AR/2009/0009702
3        AR/2012/0048621
4        AR/2010/0036913
              ...
56179    MH/2009/0003328
56180    MH/2012/0050488
56181    MH/2009/0005411
56182    MH/2010/0038456
56183    MH/2009/0017850
Name: Unique Id, Length: 56184, dtype: object

In [29]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 0
No. of unique values: 56130
No. of duplicates: 50

    Duplicate Names  Count
0   AP/2010/0035147      5
1   AP/2014/0073088      3
2   AS/2009/0000414      2
3   GJ/2011/0044924      2
4   AP/2015/0088866      2
5   UP/2014/0074389      2
6   WB/2012/0053404      2
7   UP/2011/0040795      2
8   UP/2010/0038710      2
9   UP/2013/0068986      2
10  UP/2010/0028244      2
11  GJ/2009/0015396      2
12  GJ/2010/0034014      2
13  GJ/2009/0007484      2
14  GJ/2010/0037906      2
15  DL/2009/0021777      2
16  GJ/2009/0017167      2
17  GJ/2010/0032758      2
18  GJ/2010/0030126      2
19  GJ/2009/0019241      2
20  GJ/2014/0077664      2
21  GJ/2009/0018439      2
22  MH/2012/0053030      2
23  MH/2009/0013534      2
24  TN/2014/0084401      2
25  DL/2010/0027722      2
26  OR/2009/0014969      2
27  TR/2010/0034257      2
28  AP/2010/0028447      2
29  MH/2013/0057353      2
30  CG/2013/0059134      2
31  PB/2009/0022039      2
32  RJ/2010/0034583      2
33  UP/2011/0041084      2
34  DL/2010/0027978      2
35  AS/2013/0060006      2
36  AS/2012/0052766      2
37  AP/2010/0037430      2
38  DL/2009/0004090      2
39  OR/2009/0006367      2
40  MP/2013/0059130      2
41  RJ/2013/0057320      2
42  BR/2013/0063273      2
43  MH/2013/0058628      2
44  BR/2010/0038649      2
45  BR/2013/0058386      2
46  BR/2013/0063730      2
47  UP/2010/0026395      2
48  BR/2013/0064733      2
49  MH/2013/0062179      2

In [30]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
48320,http://www.indiangoslist.com/ngo-address/navji...,NAVJIVAN KHADI GRAMODHYOG SAMAJ SEVA TRUST,GJ/2009/0007484,amit c dulera,amit c dulera,ramaben h makwna,ramaben h makwna,Charity Commissioner,Trust,GUJ/815/surendranagar,...,Gujarat,02752-233224,9.913339e+09,Navjivan khadi gramodhyog samaj seva trust Dr....,vimal_dulera03@yahoo.com,NaN,NaN,NAVJIVAN KHADI GRAMODHYOG SAMAJ SEVA TRUST is ...,This NAVJIVAN KHADI GRAMODHYOG SAMAJ SEVA TRUS...,we are worked to polyester cloth make wankar p...
48376,http://www.indiangoslist.com/ngo-address/navjy...,NAVJIVAN KHADI GRAMODHYOG SAMAJ SEVA TRUST,GJ/2009/0007484,amit c dulera,amit c dulera,ramaben h makwna,ramaben h makwna,Charity Commissioner,Trust,GUJ/815/surendranagar,...,Gujarat,02752-233224,9.913339e+09,Navjivan khadi gramodhyog samaj seva trust Dr....,vimal_dulera03@yahoo.com,NaN,NaN,NAVJIVAN KHADI GRAMODHYOG SAMAJ SEVA TRUST is ...,This NAVJIVAN KHADI GRAMODHYOG SAMAJ SEVA TRUS...,we are worked to polyester cloth make wankar p...

# Chief Functionary

In [32]:
column = dataset["Chief Functionary"]
column

0                          Mage Kamda
1                            Chairman
2                          Rakhi Bora
3                   Shri Tani Singyum
4                      Shri Hengo Bam
                     ...
56179                Krishna Shipkule
56180                   Sameer Chavan
56181    Shri Balaso Vasantrao Jagtap
56182     umesh ramchandra nilangekar
56183                    Sheela Patel
Name: Chief Functionary, Length: 56184, dtype: object

In [33]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 6
No. of unique values: 51098
No. of duplicates: 3182

              Duplicate Names  Count
0                   Secretary     96
1                   President     59
2                   SECRETARY     53
3                    Chairman     40
4                   education     33
...                       ...    ...
3177       GAJAVELLY SWAMIDAS      2
3178             Anil Malviya      2
3179                  Artists      2
3180            Sudeshna Basu      2
3181  Harsha Deelip Fulpagare      2

[3182 rows x 2 columns]

In [34]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
3537,http://www.indiangoslist.com/ngo-address/apna-...,APNA DIESEL PARIWAR,JH/2009/0011980,Sanjay Kumar,Binay Kumar,Sanjay Kunar,NaN,Sub-Registrar,Trust,11052/1V-1037,...,Jharkhand,06532-229692,9.934391e+09,"K D Market, Makatpur, Giridih",vkhaitan92@rediffmail.com,http://apnadiesel.com,NaN,APNA DIESEL PARIWAR is located in Giridih Jhar...,This APNA DIESEL PARIWAR NGO charity is workin...,Planted approx. 40000 Hectares of Jatropha Sap...
3689,http://www.indiangoslist.com/ngo-address/grami...,GRAMIN VIKAS YUVA CLUB,HR/2009/0016660,Sanjay Kumar,Sanjay Kumar,NaN,NaN,Registrar of Societies,Society,2914,...,Haryana,0184-2396524,9.896709e+09,"Village Bibipur Brahmanan Post Office Biana, T...",sanjay.bibipur@gmail.com,NaN,NaN,GRAMIN VIKAS YUVA CLUB is located in Haryana ....,This GRAMIN VIKAS YUVA CLUB NGO charity is wor...,Vocation training provided to 200 children in ...
5645,http://www.indiangoslist.com/ngo-address/dharo...,DHAROHAR SANSKRITIK SANSTHA,JH/2012/0050092,Sanjay Kumar,Reena Kumari,Sanjay Kumar,Sonali Kumari,Registrar of Societies,Society,432,...,Jharkhand,06549-242302,8.539095e+09,Complete Address along with pin code* Dharohar...,skchouhan_bonanza@yahoo.com,NaN,NaN,DHAROHAR SANSKRITIK SANSTHA is located in Boka...,This DHAROHAR SANSKRITIK SANSTHA NGO charity i...,Every year one or two plays organized with mat...
9759,http://www.indiangoslist.com/ngo-address/lok-c...,LOK CHETNA KENDRA,JH/2014/0083491,Sanjay Kumar,Sanjay Kumar,NaN,NaN,Registrar of Societies Registrar of Societies,Society Society,762 3830 - IV - 216,...,Jharkhand,09430-758195,9.430758e+09,Sanjay Kumar C/o Sri Ishwar Ram Gandhi Nagar S...,lokchetnakendra@gmail.com,NaN,NaN,LOK CHETNA KENDRA is located in Dhanbad Jharkh...,NaN,Our Society ï¿½Lok Chetna Kendraï¿½ is currently a...
13178,http://www.indiangoslist.com/ngo-address/ch-so...,CH SOHAN LAL SANTOSH CHARITABLE TRUST,DL/2009/0022423,Sanjay Kumar,Sanjay Kumar,NaN,NaN,Sub-Registrar,Trust,2452,...,Delhi,011-24646229,9.810658e+09,"House No - 1881, Jagram Mandir Lane, Near NDSE...",dhruvverma2308@rediffmail.com,NaN,NaN,CH SOHAN LAL SANTOSH CHARITABLE TRUST is locat...,This CH SOHAN LAL SANTOSH CHARITABLE TRUST NGO...,Have already held around 15 health chech-up ca...

# Chairman

In [35]:
column = dataset["Chairman"]
column

0                          Mage Kamda
1                            Chairman
2                       Ruzing Bellai
3                   Shri Tani Singyum
4                      Shri Hengo Bam
                     ...
56179                Krishna Shipkule
56180              Chandrakant Chavan
56181    Shri Balaso Vasantrao Jagtap
56182     umesh ramchandra nilangekar
56183                    Sheela Patel
Name: Chairman, Length: 56184, dtype: object

In [36]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 311
No. of unique values: 51715
No. of duplicates: 2907

              Duplicate Names  Count
0                         NaN    311
1                 Ashok Kumar     22
2                Sanjay Kumar     22
3                 Manoj Kumar     21
4                  Anil Kumar     21
...                       ...    ...
2902         Okram Ingo Singh      2
2903           REV B E SAMUEL      2
2904        SANTOSH KUMAR JHA      2
2905              Achal Singh      2
2906  Harsha Deelip Fulpagare      2

[2907 rows x 2 columns]

In [37]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
528,http://www.indiangoslist.com/ngo-address/aasth...,AASTHA MANAV SEVA SANSTHAN,BR/2014/0076873,Amresh Kumar,Rakesh Kumar,Amresh Kumar,Prem Ranjan,Registrar of Societies,Society,1704,...,Bihar,0612-2570452,9.334117e+09,1st Floor Mithulok westboring canal road,aasthamss@gmail.com,http://www.aasthamss.com,NaN,AASTHA MANAV SEVA SANSTHAN is located in Patna...,NaN,Dress distribution to children and working on ...
852,http://www.indiangoslist.com/ngo-address/assoc...,ASSOCIATION FOR RURAL AND TECHNICAL EDUCATION ...,HP/2013/0068451,Ravi Kumar,Rakesh Kumar,Ajay Kumar,Brij Dogra,Registrar of Societies,Society,4070,...,Himachal Pradesh,01970-258160,9.418431e+09,"ARTEC, Regd. Office-Village and Post Office Ma...",artec_hp@rediffmail.com,NaN,0172-2688133,ASSOCIATION FOR RURAL AND TECHNICAL EDUCATION ...,This ASSOCIATION FOR RURAL AND TECHNICAL EDUCA...,Managerial Training Programmes for the benefic...
2534,http://www.indiangoslist.com/ngo-address/himal...,HIMALAYAN NGO,HP/2014/0082826,Rakesh Kumar,Rakesh Kumar,Ashwani Kumar,Rakesh kumar,Sub-Registrar,Trust,155/2014,...,Himachal Pradesh,88945-73019,NaN,"Vill. Badhal, P.O. Bari, Teh. Jaswan kotla Dis...",himalyanngo@gmail.com,NaN,NaN,HIMALAYAN NGO is located in Kangra Himachal Pr...,NaN,Details will added on later
4188,http://www.indiangoslist.com/ngo-address/all-i...,ALL INDIA GLOBAL SOCIETY,DL/2011/0043463,Rakesh Kumar,Rakesh Kumar,Om Prakash,Geeta Devi,Registrar of Societies,Society,S-33410/1999-2000,...,Delhi,011-25936743,9.810673e+09,"103A, Sector-6,Pocket-2, DDA LIG Flat, Pappan ...",globalsocietydelhi@yahoo.co.in,NaN,NaN,ALL INDIA GLOBAL SOCIETY is located in New Del...,This ALL INDIA GLOBAL SOCIETY NGO charity is w...,"Life Skill Education, Residential Camp, Legal ..."
6688,http://www.indiangoslist.com/ngo-address/socie...,SOCIETY FOR ADVANCE RURAL TECHNOLOGY AND HEALT...,HP/2012/0051305,Rakesh Kumar,Rakesh Kumar,Shailu Devi,Sandeep Kumar,Registrar of Societies,Society,62/2007,...,Himachal Pradesh,01970-289390,9.816745e+09,"Village and Post Office Dadasiba, Tehsil Jaswa...",sarth_hp06@yahoo.com,NaN,NaN,SOCIETY FOR ADVANCE RURAL TECHNOLOGY AND HEALT...,This SOCIETY FOR ADVANCE RURAL TECHNOLOGY AND ...,The organization is working in the field of He...

# Secretary

In [38]:
column = dataset["Secretary"]
column

0                        Paksing Maling
1                                   NaN
2                             Sonem Kri
3                                   NaN
4                          Mrs Yabi Bam
                      ...
56179                siddhappa vijapure
56180                               NaN
56181    Shri Abasaheb Ganpatrao Chavan
56182       sagar ramchandra nilangekar
56183                               NaN
Name: Secretary, Length: 56184, dtype: object

In [39]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 6174
No. of unique values: 46000
No. of duplicates: 2727

            Duplicate Names  Count
0                       NaN   6174
1              Rajesh Kumar     27
2                Anil Kumar     23
3               Manoj Kumar     20
4              Sanjay Kumar     18
...                     ...    ...
2722    Shibaji Chakraborty      2
2723                 Preeti      2
2724              Dal Chand      2
2725                  Sunil      2
2726  Sudha Shamrao Sonawne      2

[2727 rows x 2 columns]

In [40]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
159,http://www.indiangoslist.com/ngo-address/anahi...,ANAHITA FOUNDATION,HP/2009/0000765,Rekha Saini,Pawan Kumar Saini,Praveen Kumar,Rekha Saini,Registrar of Societies,Trust,1815,...,Himachal Pradesh,01905-247344,9.418467e+09,ABS Globle Institute of Management & Technolog...,saini.pawankumar@rediffmail.com,http://www.absgloble.in,01905-247344,ANAHITA FOUNDATION is located in Mandi Himacha...,This ANAHITA FOUNDATION NGO charity is working...,We have been runing more then 40 institutes in...
714,http://www.indiangoslist.com/ngo-address/agras...,AGRASAR,JH/2013/0067293,Praveen Kumar,Mantosh Kumar Ojha,Praveen Kumar,Vijay Kumar,Registrar of Societies,Society,1140/07-08,...,Jharkhand,06542-222970,9.835357e+09,"AGRASAR, Quarter. No- H/45, Road No- 7, Camp -...",agrasarbokaro@rediffmail.com,NaN,NaN,AGRASAR is located in Bokaro Steel City Jharkh...,This AGRASAR NGO charity is working on Key Iss...,AGRASAR The fundamental objectives of our orga...
872,http://www.indiangoslist.com/ngo-address/anugr...,ANUGRAH VIDYA NIKETAN,CG/2010/0024756,Sunil Palaskar,Sunil Palaskar,Praveen Kumar,Madhulata,Registrar of Societies,Society,879,...,Chhattisgarh,07774-223074,9.425254e+09,Sunil Palaskar C/o Neotech Technical And Manag...,sunilpalaskar@gmail.com,http://www.neotechtimes.com,NaN,ANUGRAH VIDYA NIKETAN is located in Ambikapur ...,This ANUGRAH VIDYA NIKETAN NGO charity is work...,We are run college(Neotech Technical And Manag...
8524,http://www.indiangoslist.com/ngo-address/jhark...,JHARKHAND ACADEMIC OPEN BOARD,JH/2013/0060279,Rekha Devi,Sunil Kumar,Praveen Kumar,Prem Kumar,Sub-Registrar,Trust,4517/333,...,Jharkhand,06542-222091,9.304626e+09,"151, Bhojpur Colony, P.o- Chas, Dist- Bokaro S...",jaob2013@rediffmail.com,http://www.jaob.in,06542-222091,JHARKHAND ACADEMIC OPEN BOARD is located in Bo...,This JHARKHAND ACADEMIC OPEN BOARD NGO charity...,"to Help Poorer, Handicaped, all types of Poore..."
9385,http://www.indiangoslist.com/ngo-address/nishk...,NISHKAM SEWA SABHA,PB/2015/0085528,Mahasha Pratigya Pal,Mahasha Pratigya Pal,Praveen Kumar,Praveen Kumar,Registrar of Societies,Society,1819,...,Punjab,01675-502239,9.501075e+09,"Nishkam Sewa Sabha (Regd.), Behind Mahavir Man...",bantramhpes@gmail.com,http://www.gowshalladhuri.org,NaN,NISHKAM SEWA SABHA is located in Dhuri Punjab ...,NaN,The Sabha covers an area of 35 Kilometers arou...

# Treasurer

In [42]:
column = dataset["Treasurer"]
column

0                           Tape Maling
1                                   NaN
2                         Dalimi Tayang
3                                   NaN
4                        Shri Henya Bam
                      ...
56179                      mahesh pawar
56180                               NaN
56181    Sou Shantabai Vasantrao Jagtap
56182             vijay sudhakar jadhav
56183                               NaN
Name: Treasurer, Length: 56184, dtype: object

In [43]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 7389
No. of unique values: 44493
No. of duplicates: 2694

                 Duplicate Names  Count
0                            NaN   7389
1                   Rajesh Kumar     25
2                    Manoj Kumar     25
3                    Sunil Kumar     23
4                     Anil Kumar     22
...                          ...    ...
2689       Jayant Suryabhan Mote      2
2690  Vinita Venkatrao Godbharle      2
2691        SANDEEP KUMAR SHARMA      2
2692                  DHARAM PAL      2
2693    Ratnaprabha Subhash Wani      2

[2694 rows x 2 columns]

In [44]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
2122,http://www.indiangoslist.com/ngo-address/mask-...,MASK THEATRE,CH/2010/0028393,Vijay Kumar Ravinder Kumar,Vijay Kumar,Ravinder Kumar,Vinod Kumar,Registrar of Societies,Society,3322,...,Chandigarh,0172-2785511,9.780312e+09,"274/A, Punjab university Complex, Sector 25 Ch...",masktheatre2002@gmail.com,NaN,NaN,MASK THEATRE is located in Chandigarh Chandiga...,This MASK THEATRE NGO charity is working on Ke...,Mask theatre is a Chandigarh based theatrical ...
4029,http://www.indiangoslist.com/ngo-address/bhara...,BHARAT PRAGATI SOCIAL WELFARE SOCIETY,JH/2013/0072034,Nil Kamal Singh,Vijay Chaubey,NaN,Vinod Kumar,Registrar of Societies,Society,557/2013,...,Jharkhand,mysql_prep(0651-2530926),NaN,"Krisnand Singh , S/O- Late Jai Prakash Singh ,...",nilkamalsingh230@gmail.com,NaN,mysql_prep(-),BHARAT PRAGATI SOCIAL WELFARE SOCIETY is locat...,NaN,Use professional capacity in Human Resource De...
4565,http://www.indiangoslist.com/ngo-address/ngo-i...,NGO,HP/2009/0001543,Education,Vinod Kumar,Ashok Kumar,Vinod Kumar,Registrar of Societies,Society,2213/H,...,Himachal Pradesh,01972-278747,9.817276e+09,VPO Tauni Devi Teh. Distt. Hamirpur (H.P) 177023,siit_edu@yahoo.in,NaN,01972-278747,NGO is located in Hamirpur Himachal Pradesh . ...,This NGO NGO charity is working on Key Issues ...,running a computer centre in which we provide ...
5584,http://www.indiangoslist.com/ngo-address/cultu...,CULTURAL COMMUNICATION SOCIETY FARIDKOT,PB/2009/0007905,Jaswant Rai,Mahinder Kumar Sarswa,Rajwinder Kaur,Vinod Kumar,Registrar of Societies,Society,904,...,Punjab,01639-250332,9.876072e+09,kirat nagar faridkot,sadhanwalia@gmail.com,http://melamellianda.com,NaN,CULTURAL COMMUNICATION SOCIETY FARIDKOT is loc...,This CULTURAL COMMUNICATION SOCIETY FARIDKOT N...,This society produces many TV programmes for t...
7527,http://www.indiangoslist.com/ngo-address/publi...,PUBLIC WELFARE ORGANIZATION JAMMU,JK/2013/0059821,Soni Pandita,Soni Pandita,Darshana Devi,Vinod Kumar,Registrar of Societies,Society,4470,...,Jammu and Kashmir,0191-2503028,9.796640e+09,"Soni pandita , President Public welfare org. C...",lavishcareerpoint@gmail.com,NaN,NaN,PUBLIC WELFARE ORGANIZATION JAMMU is located i...,This PUBLIC WELFARE ORGANIZATION JAMMU NGO cha...,this org. has been working for the cause of de...

# Registered with

In [47]:
column = dataset["Registered With"]
column

0                    Registrar of Societies
1        Registrar of Cooperative Societies
2                    Registrar of Societies
3                    Registrar of Societies
4                    Registrar of Societies
                        ...
56179                  Charity Commissioner
56180                         Sub-Registrar
56181                  Charity Commissioner
56182                  Charity Commissioner
56183                  Charity Commissioner
Name: Registered With, Length: 56184, dtype: object

In [48]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 0
No. of unique values: 32
No. of duplicates: 24

                                  Duplicate Names  Count
0                          Registrar of Societies  39962
1                            Charity Commissioner   7504
2                                   Sub-Registrar   5585
3              Registrar of Cooperative Societies   1087
4       Charity Commissioner Charity Commissioner    758
5                          Registrar of Companies    498
6   Registrar of Societies Registrar of Societies    423
7                      International Organisation    177
8                     Sub-Registrar Sub-Registrar     76
9     Registrar of Societies Charity Commissioner     19
10    Charity Commissioner Registrar of Societies     15
11      Sub-Registrar Sub-Registrar Sub-Registrar     15
12   Registrar of Cooperative Societies Registrar     11
13  Charity Commissioner Charity Commissioner Cha     11
14             Sub-Registrar Charity Commissioner      6
15  Registrar of Companies Registrar of Companies      6
16  Registrar of Societies Charity Commissioner C      5
17           Registrar of Societies Sub-Registrar      3
18           Sub-Registrar Registrar of Societies      3
19  International Organisation International Orga      3
20                       Registrar of Societies -      3
21  Sub-Registrar Sub-Registrar Registrar of Soci      2
22  Sub-Registrar Sub-Registrar Charity Commissio      2
23  Charity Commissioner Charity Commissioner Reg      2

In [49]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
2184,http://www.indiangoslist.com/ngo-address/decca...,DECCAN PROFICIENT ADOPTION SOCIETY,CG/2009/0005058,CA Deepankar Samaddar,CA Deepankar Samaddar,Mihir Samaddar,Bal Krishna Naidu,Charity Commissioner Charity Commissioner Cha,Society Society Society,C.G. RAJYA-2387 CIT/RPR/Tech/12A/24/10-11 CIT/...,...,Chhattisgarh,0788-2310049,9.893910e+09,"DECCAN PROFICIENT ADOPTION SOCIETY 303, FARISH...",dpasociety.ngo@gmail.com,NaN,NaN,DECCAN PROFICIENT ADOPTION SOCIETY is located ...,This DECCAN PROFICIENT ADOPTION SOCIETY NGO ch...,We are Work in Health & physically handicapped...
4005,http://www.indiangoslist.com/ngo-address/baghe...,BAGHEAZIZI MAHELASANS THA,JH/2010/0032030,mojahida,abdulbari,nazneenbari,mdfahim,Charity Commissioner Charity Commissioner Cha,Society Society Society,201 201 201,...,Jharkhand,0657-6520934,9.504942e+09,bagheazizi mahila sanstha G.S ROAD Hussanilane...,nazneen.bari@yahoo.com,NaN,0657-2441393,BAGHEAZIZI MAHELASANS THA is located in jamshe...,This BAGHEAZIZI MAHELASANS THA NGO charity is ...,asocialnorganitionfor educational vocational s...
13313,http://www.indiangoslist.com/ngo-address/bahuj...,BAHUJAN HITAYA SHIKSHAN VA KRIDA BAHUUDDISHEYA...,MH/2013/0059075,MORE NITESH BHASKAR,MORE NITESH BHASKAR,MORE PRADIP EKNATH,SARKATE VISHVANATH KASHIRAM,Charity Commissioner Charity Commissioner Cha,Society Society Society,MAH/475/08 F 10292 BULDHANA mah/475/08,...,Maharashtra,07262-244701,9.765977e+09,"At.Post-Antrikhedekar,Tq-chikhali, Dist-Buldha...",bhskbs1@gmail.com,NaN,NaN,BAHUJAN HITAYA SHIKSHAN VA KRIDA BAHUUDDISHEYA...,This BAHUJAN HITAYA SHIKSHAN VA KRIDA BAHUUDDI...,"Cultural programme,Child health checkup camp,h..."
21302,http://www.indiangoslist.com/ngo-address/dr-an...,DR ANAND AMRUT PATIL FOUNDATION,MH/2010/0039151,Dr Anand Amrut Pati,Dr Anand Amrut Pati,Rellino Dcruz,Phelomena Dcruz,Charity Commissioner Charity Commissioner Cha,Trust Trust Society,F-13798 Maharashtra/1106/Nsk F-13798,...,Maharashtra,0253-6548050,9.561783e+09,"6, Prathibha Retreat, Asher Estate,Upnagar, Na...",rellino@hotmail.com,http://www.sahaarafoundation.com,NaN,DR ANAND AMRUT PATIL FOUNDATION is located in ...,NaN,Sahaara Foundation is a not-for-profit alcohol...
32192,http://www.indiangoslist.com/ngo-address/jeeva...,JEEVAN GOURAV PRATISHTHAN PHALTAN,MH/2013/0060158,aba ravsaheb ahirekar,aba ravsaheb ahirekar,shalini dhananjay kshirsagar,bhimrao kisan sonwalkar,Charity Commissioner Charity Commissioner Cha,Society Society Trust,maharashtra/12231/satara f-10771 (satara) PN/C...,...,Maharashtra,02166-222988,8.421045e+09,"kalubai nagar,malthan,phaltan, tal-phaltan,dis...",jeevan_gp@rediffmail.com,http://www.rediffmail.com,02166-221162,JEEVAN GOURAV PRATISHTHAN PHALTAN is located i...,This JEEVAN GOURAV PRATISHTHAN PHALTAN NGO cha...,"councling center,Business Training center,huma..."

# Type of NGO

In [50]:
column = dataset["Type of NGO"]
column

0                    Society
1        Cooperative Society
2                    Society
3                    Society
4                    Society
                ...
56179                Society
56180                  Trust
56181                Society
56182                Society
56183                  Trust
Name: Type of NGO, Length: 56184, dtype: object

In [51]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 0
No. of unique values: 22
No. of duplicates: 16

                                      Duplicate Names  Count
0                                             Society  42155
1                                               Trust  11534
2                                     Society Society    741
3                                 Cooperative Society    693
4                                         Trust Trust    459
5                                  Section 25 Company    434
6                             Society Society Society     66
7                                       Society Trust     32
8                                       Trust Society     24
9                                   Trust Trust Trust     18
10            Cooperative Society Cooperative Society      9
11              Section 25 Company Section 25 Company      4
12                                Trust Trust Society      3
13  Section 25 Company Section 25 Company Section ...      2
14                              Society Society Trust      2
15                          Cooperative Society Trust      2

In [52]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
25102,http://www.indiangoslist.com/ngo-address/calcu...,CALCUTTA PROMOTIONS,WB/2010/0038730,A V Iyengar,Justice M K Mukherjee Retired,NaN,NaN,Registrar of Companies Registrar of Companies,Section 25 Company Section 25 Company Section ...,U45202 WB 2003 PTC O 96234 U45202 WB 2003 PTC ...,...,West Bengal,033-23372989,9.831873e+09,"Calcutta Promotions 147 Block-G, New Alipore K...",iyengar.viji@gmail.com,http://www.happeningskolkata.org,033-23375137,CALCUTTA PROMOTIONS is located in Kolkata West...,This CALCUTTA PROMOTIONS NGO charity is workin...,Calcutta Promotions is a not for profit organi...
27895,http://www.indiangoslist.com/ngo-address/grey-...,GREY SIM LEARNINGS FOUNDATION,MH/2014/0083485,Col Pankaj Goel,Amit Gupta,NaN,NaN,Registrar of Companies Sub-Registrar Sub-Regi,Section 25 Company Section 25 Company Section ...,U80900MH2013NPL251497 47060 Under Section 12A ...,...,Maharashtra,022-25181012,NaN,"A 303-304, Kailas Industrial Complex, Parksite...",pankaj@indiarescue.org,http://www.indiarescue.org,022-25181013,GREY SIM LEARNINGS FOUNDATION is located in Mu...,NaN,"To help academic institutions, schools, corpor..."

# Registration Number

In [53]:
column = dataset["Registration Number"]
column

0                           SR/ITA/2271
1                           SR/ITS/3251
2                           SR ITA 2849
3                           SR/ITA/8728
4                           SR/ITA/2616
                      ...
56179                  MAHA/8416/SATARA
56180                              1783
56181    Maha/190/2007, F- 11565/Sangli
56182                MAH/79/2003/F/8053
56183                        BOM 798/84
Name: Registration Number, Length: 56184, dtype: object

In [54]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 4
No. of unique values: 49200
No. of duplicates: 2705

     Duplicate Names  Count
0                 25     18
1                137     17
2                 59     16
3                 77     16
4                 72     16
...              ...    ...
2700     166/2005-06      2
2701            1510      2
2702             492      2
2703            1467      2
2704       2161/5119      2

[2705 rows x 2 columns]

In [58]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
1799,http://www.indiangoslist.com/ngo-address/anard...,ANARDE FOUNDATION KAPARADA WOMEN WING,GJ/2012/0051910,Chetanbhai I Thakor,Kapoorbhai Chandria,NaN,NaN,Charity Commissioner,Trust,E 7146,...,Gujarat,02633-241185,9.913460e+09,"Anarde Foundation, Kaparada (Women Wing), Hath...",shauryabs@gmail.com,http://www.anardefoundation.org,02633-241185,ANARDE FOUNDATION KAPARADA WOMEN WING is locat...,This ANARDE FOUNDATION KAPARADA WOMEN WING NGO...,Agricultural activities including cultivation ...
1807,http://www.indiangoslist.com/ngo-address/anard...,ANARDE FOUNDATION,GJ/2010/0027971,Mr Kapoorbhai Chanderia,Mr Kapoorbhai Chanderia,Mr Anish K Chandaria,Mr Hirubhai Patel,Charity Commissioner,Trust,E-7146,...,Gujarat,0260-6451419,9.925501e+09,"4, Master Patel Building, 1st floor, sulpad ro...",anardefoundationvapi@yahoo.com,NaN,NaN,ANARDE FOUNDATION is located in Vapi Gujarat ....,This ANARDE FOUNDATION NGO charity is working ...,ANaRDE foundatrion has competed 28 years of it...
1811,http://www.indiangoslist.com/ngo-address/aadha...,AADHAR FOUNDATION,MH/2013/0059268,Vikas Sandipan Kharat,Vikas Sandipan Kharat,NaN,NaN,Charity Commissioner,Society,1206/2011/GBBSD,...,Maharashtra,022-25168630,9.870260e+09,"Room no.50,Gajanan society, lalbatti,hanuman t...",adv.vikaskharat@gmail.com,NaN,NaN,AADHAR FOUNDATION is located in Mumbai Maharas...,This AADHAR FOUNDATION NGO charity is working ...,we have done work in the field of Dalit uplift...
2196,http://www.indiangoslist.com/ngo-address/aadha...,AADHAR SKILL DEVELOPMENT TRUST,MH/2012/0050181,Nandan Srivastava,Kanaiya Dayaram Katariya,NaN,NaN,Charity Commissioner,Trust,E-28555,...,Maharashtra,022-25914423,NaN,"Oswal Bhawan, Block No.3, S. N. Road, Mulund W...",amit@aadharskilldevelopment.org,http://www.aadharskilldevelopment.org,NaN,AADHAR SKILL DEVELOPMENT TRUST is located in M...,This AADHAR SKILL DEVELOPMENT TRUST NGO charit...,Enable the lesser privileged members of the co...
2198,http://www.indiangoslist.com/ngo-address/aadhu...,AADHUNIK STREE VIKAS PRATISTHAN,MH/2009/0022843,vidya yashwant Sarmalkar,vidya yashwant Sarmalkar,Suvarna Jagannath Chikane,Geeta yashwant Sarmalkar,Charity Commissioner,Trust,"MAH,MUM/1463/2005/GBBSD",...,Maharashtra,09833-396899,9.322972e+09,"1/6, NAVJEEVAN NAGAR, GANESH MARG,VIKHROLI (E)...",asvp2005@rediffmail.com,NaN,NaN,AADHUNIK STREE VIKAS PRATISTHAN is located in ...,This AADHUNIK STREE VIKAS PRATISTHAN NGO chari...,OBJECT: - To secure participation of Youth & W...

# City of Registration

In [56]:
column = dataset["City of Registration"]
column

0          Itanagar
1        Naharlagun
2          Itanagar
3           Itnagar
4          Itanagar
            ...
56179        Satara
56180     New Delhi
56181        Sangli
56182    aurangabad
56183        Mumbai
Name: City of Registration, Length: 56184, dtype: object

In [57]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 268
No. of unique values: 6124
No. of duplicates: 2389

           Duplicate Names  Count
0                  Kolkata   2630
1                  KOLKATA   1745
2                    Delhi   1354
3                  Lucknow   1103
4                    Patna   1050
...                    ...    ...
2384             Lakhimpur      2
2385             berhampur      2
2386  RANGA REDDY DISTRICT      2
2387                Cumbum      2
2388           Ahmedanagar      2

[2389 rows x 2 columns]

In [59]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
1799,http://www.indiangoslist.com/ngo-address/anard...,ANARDE FOUNDATION KAPARADA WOMEN WING,GJ/2012/0051910,Chetanbhai I Thakor,Kapoorbhai Chandria,NaN,NaN,Charity Commissioner,Trust,E 7146,...,Gujarat,02633-241185,9.913460e+09,"Anarde Foundation, Kaparada (Women Wing), Hath...",shauryabs@gmail.com,http://www.anardefoundation.org,02633-241185,ANARDE FOUNDATION KAPARADA WOMEN WING is locat...,This ANARDE FOUNDATION KAPARADA WOMEN WING NGO...,Agricultural activities including cultivation ...
1807,http://www.indiangoslist.com/ngo-address/anard...,ANARDE FOUNDATION,GJ/2010/0027971,Mr Kapoorbhai Chanderia,Mr Kapoorbhai Chanderia,Mr Anish K Chandaria,Mr Hirubhai Patel,Charity Commissioner,Trust,E-7146,...,Gujarat,0260-6451419,9.925501e+09,"4, Master Patel Building, 1st floor, sulpad ro...",anardefoundationvapi@yahoo.com,NaN,NaN,ANARDE FOUNDATION is located in Vapi Gujarat ....,This ANARDE FOUNDATION NGO charity is working ...,ANaRDE foundatrion has competed 28 years of it...
1811,http://www.indiangoslist.com/ngo-address/aadha...,AADHAR FOUNDATION,MH/2013/0059268,Vikas Sandipan Kharat,Vikas Sandipan Kharat,NaN,NaN,Charity Commissioner,Society,1206/2011/GBBSD,...,Maharashtra,022-25168630,9.870260e+09,"Room no.50,Gajanan society, lalbatti,hanuman t...",adv.vikaskharat@gmail.com,NaN,NaN,AADHAR FOUNDATION is located in Mumbai Maharas...,This AADHAR FOUNDATION NGO charity is working ...,we have done work in the field of Dalit uplift...
2196,http://www.indiangoslist.com/ngo-address/aadha...,AADHAR SKILL DEVELOPMENT TRUST,MH/2012/0050181,Nandan Srivastava,Kanaiya Dayaram Katariya,NaN,NaN,Charity Commissioner,Trust,E-28555,...,Maharashtra,022-25914423,NaN,"Oswal Bhawan, Block No.3, S. N. Road, Mulund W...",amit@aadharskilldevelopment.org,http://www.aadharskilldevelopment.org,NaN,AADHAR SKILL DEVELOPMENT TRUST is located in M...,This AADHAR SKILL DEVELOPMENT TRUST NGO charit...,Enable the lesser privileged members of the co...
2198,http://www.indiangoslist.com/ngo-address/aadhu...,AADHUNIK STREE VIKAS PRATISTHAN,MH/2009/0022843,vidya yashwant Sarmalkar,vidya yashwant Sarmalkar,Suvarna Jagannath Chikane,Geeta yashwant Sarmalkar,Charity Commissioner,Trust,"MAH,MUM/1463/2005/GBBSD",...,Maharashtra,09833-396899,9.322972e+09,"1/6, NAVJEEVAN NAGAR, GANESH MARG,VIKHROLI (E)...",asvp2005@rediffmail.com,NaN,NaN,AADHUNIK STREE VIKAS PRATISTHAN is located in ...,This AADHUNIK STREE VIKAS PRATISTHAN NGO chari...,OBJECT: - To secure participation of Youth & W...

# State of Registration

In [63]:
column = dataset["State of Registration"]
column

0        Arunachal Pradesh
1        Arunachal Pradesh
2        Arunachal Pradesh
3        Arunachal Pradesh
4        Arunachal Pradesh
               ...
56179          Maharashtra
56180                Delhi
56181          Maharashtra
56182          Maharashtra
56183          Maharashtra
Name: State of Registration, Length: 56184, dtype: object

In [61]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 266
No. of unique values: 91
No. of duplicates: 73

                                      Duplicate Names  Count
0                                       Uttar Pradesh   9077
1                                         Maharashtra   5564
2                                         West Bengal   5481
3                                               Delhi   3596
4                                      Andhra Pradesh   3276
..                                                ...    ...
68                                      Punjab Punjab      2
69                                    Manipur Manipur      2
70                  Himachal Pradesh Himachal Pradesh      2
71  Jammu and Kashmir Jammu and Kashmir Jammu and ...      2
72                            Gujarat Gujarat Gujarat      2

[73 rows x 2 columns]

In [62]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
85,http://www.indiangoslist.com/ngo-address/bheem...,BHEEMSINGH,AN/2011/0042723,bheemsingh,bheemsingh,bheemsingh,bheemsingh,Registrar of Societies,Section 25 Company,4358340958304,...,Andaman and Nicobar Island,202-03804349,NaN,"lakkad pura, bamboo road, near trees",saloni92146@yahoo.com,NaN,NaN,BHEEMSINGH is located in bheemsingh Andaman an...,This BHEEMSINGH NGO charity is working on Key ...,bheemsingh bheemsingh bheemsingh bheemsingh bh...
230,http://www.indiangoslist.com/ngo-address/karun...,KARUNYA CHARITABLE SOCIETY,KL/2012/0055656,Fr Daniel Kuzhithadathil,C S Ramachandran Nair,Adv Annamma George,A Vijayan,Registrar of Societies,Society,p-455/96,...,Kerala,0472-2585996,9.447221e+09,KARUNYA CHARITABLE SOCIETY KARUNYA BHAVAN VETT...,karunyakerala@gmail.com,NaN,0472-2585996,KARUNYA CHARITABLE SOCIETY is located in VATTA...,This KARUNYA CHARITABLE SOCIETY NGO charity is...,We are taking up any suitable developmental ac...
231,http://www.indiangoslist.com/ngo-address/forum...,FORUM FOR RURAL AND URBAN INTEGRATED TRANSFORM...,KL/2010/0034501,Muhamed Ansari N,Khan Shajahan,Adv Muhamed Ansari,Balu B Pillai,Registrar of Societies,Society,P-439/07,...,Kerala,0468-2320426,9.446915e+09,"Kanraj Bhavan, Makkam Kunnu PO. Pathanamthitta...",ansaripta@gmail.com,NaN,NaN,FORUM FOR RURAL AND URBAN INTEGRATED TRANSFORM...,This FORUM FOR RURAL AND URBAN INTEGRATED TRAN...,Research on socio demographic conditions ofUrb...
234,http://www.indiangoslist.com/ngo-address/aarog...,AAROGYA CHARITABLE FOUNDATION TRUST,KL/2014/0084114,SIBY THARAKAN,SIBY THARAKAN,SOJAN K MATHEW,SOJAN K MATHEW,Sub-Registrar,Trust,IV/161/2014,...,Kerala,0481-2362507,9.446030e+09,AAROGYA CHARITABLE FOUNDATION TRUST THARAKAN H...,aarogya2008@gmail.com,NaN,NaN,AAROGYA CHARITABLE FOUNDATION TRUST is located...,NaN,"(a) To establish, maintain or grant aid to hom..."
235,http://www.indiangoslist.com/ngo-address/baker...,BAKER CHARITABLE TRUST AND RESEARCH CENTRE,KL/2010/0031565,Rev P T George,Cherian C Itticherian,Josemon George,Aniamma Joseph,Charity Commissioner,Trust,114/06/2006,...,Kerala,0481-2537771,9.895870e+09,Baker Charitable Trust and reserch Centre Chem...,drcherian.chemplavil@gmail.com,http://bakercharitabletrust.org,NaN,BAKER CHARITABLE TRUST AND RESEARCH CENTRE is ...,This BAKER CHARITABLE TRUST AND RESEARCH CENTR...,development of charitable hospital named KARUN...

# Date of Registration

In [64]:
column = dataset["Date of Registration"]
column

0        24-02-2004
1        13-03-2006
2        28-06-2005
3        03-11-2004
4        30-12-2004
            ...
56179    25-03-2004
56180    20-04-2012
56181    28-03-2007
56182    27-01-2003
56183    13-12-1984
Name: Date of Registration, Length: 56184, dtype: object

In [65]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 36
No. of unique values: 12815
No. of duplicates: 8349

            Duplicate Names  Count
0                31-03-2009     49
1                05-02-2009     39
2                31-03-2010     38
3                       NaN     36
4                31-12-2007     33
...                     ...    ...
8344             28-04-2013      2
8345             02-01-1978      2
8346             01-05-2013      2
8347             18-09-1982      2
8348  07-04-2010 20-09-2010      2

[8349 rows x 2 columns]

In [66]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
1216,http://www.indiangoslist.com/ngo-address/al-aq...,AL AQSA EDUCATIONAL AND WELFARE TRUST,KA/2012/0048223,AFSHAN PARVEEN,M S MURTAZA,ARSHAD MOHIUDDIN,MD MASTAN,Sub-Registrar,Trust,C21/2008-09-BKIV,...,Karnataka,08483-270110,9.986253e+09,AL AQSA EDUCATIONAL AND WELFARE TRUST C/O MD M...,mastan.suzanfalak38@gmail.com,NaN,NaN,AL AQSA EDUCATIONAL AND WELFARE TRUST is locat...,This AL AQSA EDUCATIONAL AND WELFARE TRUST NGO...,We are working on Developement of Educational ...
1663,http://www.indiangoslist.com/ngo-address/aryav...,ARYAVARTA BRAHMIN MAHASABHA,HR/2009/0000400,ram gopal sharma,ram gopal sharma,yogender pandey,rakesh mishra,Registrar of Societies,Society,139,...,Haryana,0180-2634603,9.812330e+09,"parshuram bhawan, vikas nagar, devi mandir bar...",abm.panipat@gmail.com,NaN,NaN,ARYAVARTA BRAHMIN MAHASABHA is located in pani...,This ARYAVARTA BRAHMIN MAHASABHA NGO charity i...,we are providingall kind help for inds. labour...
8139,http://www.indiangoslist.com/ngo-address/bheem...,BHEEMA URBAN AND RURAL DEVELOPMENT ORGANIZATION,KA/2011/0042159,Marling Honguntikar,Prakash,Marling Honguntikar,Devindra,Registrar of Cooperative Societies,Society,1281,...,Karnataka,08474-290482,9.964644e+09,Secretary Marling Bheema Urban and Rural Devel...,mhonguntikar@gmail.com,NaN,NaN,BHEEMA URBAN AND RURAL DEVELOPMENT ORGANIZATIO...,This BHEEMA URBAN AND RURAL DEVELOPMENT ORGANI...,"Training on Women education, Awareness on fore..."
8143,http://www.indiangoslist.com/ngo-address/bheem...,BHEEMA URBAN AND RURAL DEVELOPMENT ORGANIZATION,KA/2013/0071116,secretary,Prakash,NaN,Devindra,Sub-Registrar,Society,1281/2008,...,Karnataka,mysql_prep(08476-202090),9.964644e+09,Bheema urban and rural development organizatio...,bheemango222@gmail.com,NaN,mysql_prep(-),BHEEMA URBAN AND RURAL DEVELOPMENT ORGANIZATIO...,NaN,"women empowering programme, health check up ca..."
10203,http://www.indiangoslist.com/ngo-address/biswo...,BISWOLAXMI SELF HELP GROUP,OR/2013/0061215,Manjusarani Pattnaik,Janaki Barik,Manjusarani Pattniak,kunilata Naik,Registrar of Societies,Society,7053-103,...,Orissa,0675-2545482,7.894277e+09,"Biswolaxmi SHG At- Issanpada, Po- Sukal Via- S...",bshg.org@gmail.com,NaN,NaN,BISWOLAXMI SELF HELP GROUP is located in Oriss...,This BISWOLAXMI SELF HELP GROUP NGO charity is...,"water and sanitation, rural sports, training a..."

# City

In [67]:
column = dataset["City"]
column

0             Upper Subansiri
1        Lower Subansiri Dist
2                        Tezu
3                    Itanagar
4                         NaN
                 ...
56179                  Satara
56180                  Mumbai
56181                  Sangli
56182              Aurangabad
56183                  Mumbai
Name: City, Length: 56184, dtype: object

In [68]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 2373
No. of unique values: 6627
No. of duplicates: 2607

           Duplicate Names  Count
0                      NaN   2373
1                  Kolkata   2164
2                  Lucknow   1489
3                New Delhi   1470
4                    Delhi   1450
...                    ...    ...
2602              Bhanpuri      2
2603           Bhagawanpur      2
2604               Neyyoor      2
2605  South Twenty Four Pg      2
2606               Nirjuli      2

[2607 rows x 2 columns]

In [69]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
130,http://www.indiangoslist.com/ngo-address/aadha...,AADHAR EDUCATION AND CHARETABLE TRUST,GJ/2009/0012776,NITABEN J PAREKH,NITABEN J PAREKH,BHAVINI R PARIKH,SHAILESH A GANDHI,Charity Commissioner,Society,guj/8901/ahmedabad,...,Gujarat,079-27454451,9.426725e+09,"N-21 Aakansha Flates,Nr. Sola Rly.Crossing, Gh...",aadhartrust@yahoo.in,NaN,NaN,AADHAR EDUCATION AND CHARETABLE TRUST is locat...,This AADHAR EDUCATION AND CHARETABLE TRUST NGO...,education filed womens awerness.activites rela...
132,http://www.indiangoslist.com/ngo-address/aadha...,AADHAR,GJ/2009/0005831,avni varia,pallavi varia,avni varia,shrenik vaishnav,Charity Commissioner,Trust,E/16408,...,Gujarat,079-26612292,9.879773e+09,"C / 281, ï¿½RangNivasï¿½ First floor, Bhavna Tenam...",mail_aadhar@yahoo.co.in,http://www.aadhar-india.org,NaN,AADHAR is located in ahmedabad Gujarat . AADHA...,This AADHAR NGO charity is working on Key Issu...,AADHAR is an initiative to perform & promote v...
291,http://www.indiangoslist.com/ngo-address/aai-s...,AAI SHRI KHODIYAR KHADI GRAMODHYOG SANGH,GJ/2009/0019709,Lasiben Babarbhai Rabari,Lasiben Babarbhai Rabari,Shivabhai Ramabhai Rabari,Arjunbhai Sanakarbhai Rabari,Charity Commissioner,Trust,F/3108/Ahmedabad,...,Gujarat,079-26760661,9.714631e+09,"G/4 Bhanuram Flats, Vejalpur, Vastrapur Rly. C...",akhkhgs@rediff.com,NaN,NaN,AAI SHRI KHODIYAR KHADI GRAMODHYOG SANGH is lo...,This AAI SHRI KHODIYAR KHADI GRAMODHYOG SANGH ...,"Women & Child Development, Education, Income g..."
293,http://www.indiangoslist.com/ngo-address/aarti...,AARTI MAHILA VIKAS SANGH,GJ/2011/0040405,Aartiben B Parmar,Aartiben B Parmar,Jayaben J Parmar,Rekhaben R Vaja,Charity Commissioner,Trust,F-7566,...,Gujarat,079-25398290,9.714530e+09,"1, Sarvoday Baug, Panch Bungla, Gitamadir Nala...",aarti-mahila@in.com,NaN,NaN,AARTI MAHILA VIKAS SANGH is located in Ahmedab...,This AARTI MAHILA VIKAS SANGH NGO charity is w...,Attached Along With
294,http://www.indiangoslist.com/ngo-address/aarti...,AARTI MAHILA VIKAS SANGH,GJ/2013/0069423,Aartiben Bhanjibhai Parmar,Aartiben Bhanjibhai Parmar,NaN,NaN,Charity Commissioner,Trust,F/7566/Ahmedabad,...,Gujarat,091-97241328,NaN,"Aarti Mahila Vikas Sangh,1,Sarvoday Baug,Panch...",amvsahmedabad@gmail.com,NaN,NaN,AARTI MAHILA VIKAS SANGH is located in Ahmedab...,This AARTI MAHILA VIKAS SANGH NGO charity is w...,"Women empowerment,Women Devlopment,Civil Issue..."

# State

In [70]:
column = dataset["State"]
column

0        Arunachal Pradesh
1        Arunachal Pradesh
2        Arunachal Pradesh
3        Arunachal Pradesh
4        Arunachal Pradesh
               ...
56179          Maharashtra
56180          Maharashtra
56181          Maharashtra
56182          Maharashtra
56183          Maharashtra
Name: State, Length: 56184, dtype: object

In [71]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 0
No. of unique values: 35
No. of duplicates: 35

               Duplicate Names  Count
0                Uttar Pradesh   9293
1                  Maharashtra   6374
2                  West Bengal   5509
3               Andhra Pradesh   3334
4                        Delhi   3290
5                   Tamil Nadu   3087
6                        Bihar   2871
7                       Orissa   2805
8               Madhya Pradesh   2703
9                      Gujarat   2700
10                   Karnataka   2312
11                   Rajasthan   2000
12                       Assam   1679
13                   Jharkhand   1184
14                      Kerala   1156
15                     Manipur   1072
16                     Haryana    823
17                  Uttarkhand    751
18           Jammu and Kashmir    624
19                      Punjab    546
20                Chhattisgarh    505
21            Himachal Pradesh    323
22                    Nagaland    266
23                     Tripura    202
24           Arunachal Pradesh    173
25                   Meghalaya    161
26                  Puducherry    100
27                  Chandigarh     94
28                         Goa     73
29                      Sikkim     72
30                     Mizoram     54
31  Andaman and Nicobar Island     23
32                 Lakshadweep     10
33      Dadra and Nagar Haveli      8
34               Daman and Diu      7

In [72]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
97,http://www.indiangoslist.com/ngo-address/jhark...,JHARKHAND JYOTI,JH/2011/0042327,JAYANTA MANDAL,BHOLA SHANKAR GUPTA,JAYANTA MANDAL,MRS SULATA MANDAL,Registrar of Societies,Society,598,...,Jharkhand,0657-2281833,9.204736e+09,"Jharkhand Jyoti, C/O B K Mandal Zone No: 6B, H...",jharkhandjyoti@gmail.com,http://www.jharkhandjyoti.org.in,0657-2281833,JHARKHAND JYOTI is located in JAMSHEDPUR Jhark...,This JHARKHAND JYOTI NGO charity is working on...,"Livilehood prototype, Tribal Affairs, Agricult..."
99,http://www.indiangoslist.com/ngo-address/sarna...,SARNA INSTITUTE OF SOCIAL SERVICE,JH/2009/0012574,Mahadeb Murmu,Mahadeb Murmu,Khelaram Murmu,BijoyKumar Munda,Registrar of Societies,Society,1090,...,Jharkhand,06594-233506,9.204140e+09,"Sarna Institute of Social Service , Chakulia A...",sarnainstitute@gmail.com,http://www.sarnainstitute.com,NaN,SARNA INSTITUTE OF SOCIAL SERVICE is located i...,This SARNA INSTITUTE OF SOCIAL SERVICE NGO cha...,Sarna Institute of Social Service has been wor...
102,http://www.indiangoslist.com/ngo-address/jhark...,JHARKHAND NETWORK FOR PEOPLE LIVING WITH HIV,JH/2013/0066385,Bahadur Yadav,Bahadur Yadav,NaN,NaN,Registrar of Societies,Society,408/2006-07,...,Jharkhand,0651-995519,NaN,"opposite paper house, indrapuri chow, hazariba...",jogritiabhiyan@gmail.com,NaN,NaN,JHARKHAND NETWORK FOR PEOPLE LIVING WITH HIV i...,This JHARKHAND NETWORK FOR PEOPLE LIVING WITH ...,HIV/ AIDS people helping them and to give all ...
103,http://www.indiangoslist.com/ngo-address/ideal...,IDEAL AND NATURAL DISCIPLINARY ORGANIZATION INDO,JH/2012/0051747,Pawan Kumar Sharma,Ramnath Ram,Pawan Kumar Sharma,Sourabh Kumar Singh,Registrar of Societies,Society,1074/2010-11,...,Jharkhand,0651-2290154,9.308404e+09,"Chandani Chowk, Hatia P.O.- Hatia P.S.- Jagann...",indoranchi@gmail.com,http://Indoranchi.in,0651-2290154,IDEAL AND NATURAL DISCIPLINARY ORGANIZATION IN...,This IDEAL AND NATURAL DISCIPLINARY ORGANIZATI...,Women Empowerment Programme SHG Formation And ...
104,http://www.indiangoslist.com/ngo-address/a-yug...,A YUGANTAR BHARATI,JH/2009/0013198,Aashish Sheetal,Madhu,Aashish Sheetal,Ashok Goel,Registrar of Societies,Society,968,...,Jharkhand,0651-6003372,9.835198e+09,"Post Box no - 32, Namkum post office, Sidroul,...",yugantarbharati@gmail.com,http://yugantarbharati.org.in,0651-2260787,A YUGANTAR BHARATI is located in Ranchi Jharkh...,This A YUGANTAR BHARATI NGO charity is working...,We are working in the field of Environmental C...

# Telephone

In [73]:
column = dataset["Telephone"]
column

0        0360-2292635
1         9199-100015
2        03804-222878
3        0379-2224167
4        0379-5222241
             ...
56179    02162-237192
56180    022-28063468
56181    02344-247114
56182    0240-2481857
56183    022-23865053
Name: Telephone, Length: 56184, dtype: object

In [76]:
# Number of missing values
print("Nulls:", sum(column.isnull()))

print("No. of unique values:", len(column.unique()))

# Drop nulls and remove hyphen and mysql_prep()
column = column.dropna()
cleaned_column = [re.sub('[^0-9]','', row) for row in column]
column = pd.Series(cleaned_column)



# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
del duplicates["0000000000000"]
del duplicates["00000000000"]
del duplicates["0000000000"]
del duplicates["000000000"]
del duplicates["00000000"]
print("No. of Duplicates:", len(duplicates))

table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Off phone1 numbers", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)

# Lenght of numbers
print("Lengths:", table["Duplicate Off phone1 numbers"].apply(len).unique())

table

Nulls: 0
No. of unique values: 48585
No. of Duplicates: 4217
Lengths: [11  0  9 10 12  8]

     Duplicate Off phone1 numbers  Count
0                     03852321291     58
1                     06122231820     58
2                     02452248528     56
3                     03640000000     52
4                     05223213944     41
...                           ...    ...
4212                  02634262141      2
4213                  07922818473      2
4214                  03174256932      2
4215                  03210220327      2
4216                  01129521977      2

[4217 rows x 2 columns]

In [77]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
11074,http://www.indiangoslist.com/ngo-address/aapan...,AAPAN,WB/2014/0084234,MD Habibar Rahaman,Taj Mohammad,MD Habibar Rahaman,MD Sadik Sobhan,Registrar of Societies,Society,S/IL/35485,...,West Bengal,033-25362347,9.647111e+09,"Aminpur Bazer, P.O:- Sondhalia, P.S:- Shason, ...",aapan.ngo@gmail.com,NaN,NaN,AAPAN is located in Barasat West Bengal . AAPA...,NaN,"Education, Health, Woman, Development Empowerm..."
11097,http://www.indiangoslist.com/ngo-address/aamar...,AAMAR SANKALPA,WB/2009/0014490,CHANDRANI DUTTA CHAKRABORTY,SUBAL CHANDRA DAS,CHANDRANI DUTTA CHAKRABORTY,NASIR MANDAL,Registrar of Societies,Society,S/IL/26721,...,West Bengal,033-25362347,9.434828e+09,"EAST KAMARTHUBA,P-CHAKI ROAD, P.O- HABRA, P.S-...",aamarsankalpa@rediffmail.com,NaN,NaN,AAMAR SANKALPA is located in HABRA West Bengal...,This AAMAR SANKALPA NGO charity is working on ...,EDUCATION : OUR THIS VERY ORGANISATION HAS BEE...
18045,http://www.indiangoslist.com/ngo-address/balid...,BALIDANGRI AVINANDAN SANGHA,WB/2009/0014708,AROBINDA KAR,ANUP MAITY,AROBINDA KAR,CHANDAN BERA,Registrar of Societies,Society,S/76804/94-95,...,West Bengal,033-25362347,9.732561e+09,"VILL: BALIDANGA, PO + PS: PANSKURA, DIST: PURB...",b.as33@yahoo.in,NaN,NaN,BALIDANGRI AVINANDAN SANGHA is located in MEDI...,This BALIDANGRI AVINANDAN SANGHA NGO charity i...,Our organization is continuing a medical centr...
20721,http://www.indiangoslist.com/ngo-address/barur...,BARURBHERI NETAJI SANGHA,WB/2009/0014684,SK SABIR ALI,SK SAIFUL,SK SABIR ALI,SK JAMAL,Registrar of Societies,Society,S/1L/38532/2006-07,...,West Bengal,033-25362347,NaN,"VIIL- BARURBHERI, P.O- GOPINATHPUR, P.S- BHAGW...",bns1290@yahoo.in,NaN,NaN,BARURBHERI NETAJI SANGHA is located in TAMLUK ...,This BARURBHERI NETAJI SANGHA NGO charity is w...,Our organization is continuing a medical centr...
20736,http://www.indiangoslist.com/ngo-address/barur...,BARURBHERI NEW STAR CLUB,WB/2009/0014692,BABULAL KHAN,BABULAL KHAN,SK MUJIBAR,SOMED SAHA,Registrar of Societies,Society,S/1L/38549/2006-07,...,West Bengal,033-25362347,NaN,"VILL-BARURBHERI, P.O- GOPINATHPUR, P.S- BHAGWA...",c.bn41@yahoo.in,NaN,NaN,BARURBHERI NEW STAR CLUB is located in MEDINIP...,This BARURBHERI NEW STAR CLUB NGO charity is w...,Our this very organization has been running an...

# Mobile

In [78]:
column = dataset["Mobile"]
column

0        9.436054e+09
1                 NaN
2        9.436227e+09
3                 NaN
4        9.436411e+09
             ...
56179    9.860925e+09
56180    9.320303e+09
56181    9.890202e+09
56182    9.422294e+09
56183             NaN
Name: Mobile, Length: 56184, dtype: float64

In [80]:
# Number of missing values
print("Nulls:", sum(column.isnull()))

print("No. of unique values:", len(column.unique()))

# Drop nulls and remove float and convert to str.
column = column.dropna().astype(int).astype(str)

# Lenght of mobile number
print("Lengths:", column.apply(len).unique())

# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of Duplicates:", len(duplicates))

table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Mobile numbers", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Nulls: 0
No. of unique values: 45459
Lengths: [10 11  9  1]
No. of Duplicates: 3400

     Duplicate Mobile numbers  Count
0                           0     24
1                  9935718528     18
2                  9423444562     17
3                  9856084583     14
4                  9838461243     11
...                       ...    ...
3395               9903412603      2
3396               9443408084      2
3397               9732624250      2
3398               9443321464      2
3399               9860802181      2

[3400 rows x 2 columns]

In [83]:
dataset[dataset["Mobile"] == int(table.iloc[0,0])].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
1279,http://www.indiangoslist.com/ngo-address/allia...,ALLIANCE FOR COLLECTIVE EMPOWERMENT,MN/2010/0037946,Thangjahao Haokip,Lhingkim Haokip,Thangjahao Haokip,Ngahoryang Shingnaisul,Registrar of Societies,Society,67 of 2005,...,Manipur,0385-2451984,0.0,Yamthong Bulding New Lambulane Bazar Imphal ea...,acemanipur@gmail.com,NaN,0000-0000000,ALLIANCE FOR COLLECTIVE EMPOWERMENT is located...,This ALLIANCE FOR COLLECTIVE EMPOWERMENT NGO c...,Awareness Programme on HIV & AIDS Legal Awaren...
7236,http://www.indiangoslist.com/ngo-address/counc...,COUNCIL FOR TECHNICAL EDUCATION,TR/2009/0013441,Chairman,Sukla Goswami,Mridul Deb,Kamal Das,Registrar of Societies,Society,3502,...,Tripura,0381-2201441,0.0,Madhupur Bishalgarh West tripura pin.-799100,cte_tripura@rediff.com,NaN,NaN,COUNCIL FOR TECHNICAL EDUCATION is located in ...,NaN,We are providing vocational courses like as Ra...
8538,http://www.indiangoslist.com/ngo-address/ashra...,ASHRAYA JAN SEVA SAMITI,MP/2013/0060400,Sarika,Laxmi devi,Sarika,Sanjay,Registrar of Societies,Society,01/01/01/16798/06,...,Madhya Pradesh,0755-0000000,0.0,"Near Heniman Homyopethi collage, Gandhi nagar ...",sarika.chaturvedi28@gmail.com,NaN,NaN,ASHRAYA JAN SEVA SAMITI is located in Bhopal M...,This ASHRAYA JAN SEVA SAMITI NGO charity is wo...,"Women And Child Welfare, Drinking water, Educa..."
10188,http://www.indiangoslist.com/ngo-address/ggg-i...,GGG,AS/2009/0002447,hhhh hhh,hhhh jkjkk,jjjk kkkkl,hhjhjskkkk,Registrar of Societies,Society,222233hhjhjjj,...,Assam,000-000000,0.0,hghjgjj,kjhkjkjj@gmail.com,NaN,NaN,GGG is located in kjhkjhk Assam . GGG is regis...,This GGG NGO charity is working on Key Issues ...,hhhhhhhhhhhhhh
13876,http://www.indiangoslist.com/ngo-address/image...,IMAGE EDUCATIONAL AND LITERARY CULTURAL SOCIAL...,KA/2009/0013477,ZAKIRHUSEN,SALEEMA KOTWAL,ZAKIRHUSEN,SHIVANAND IRAPPA APZALPUR,Registrar of Societies,Society,BIJ-S82-2008-09,...,Karnataka,08352-000000,0.0,"BAGEWADI COMPLEX, BAGALKOT ROAD, Bijapur",imageassn@ymail.com,NaN,NaN,IMAGE EDUCATIONAL AND LITERARY CULTURAL SOCIAL...,This IMAGE EDUCATIONAL AND LITERARY CULTURAL S...,TOTALY SERVE FOR HUMANITY and Improve the Poor...

# Address

In [84]:
column = dataset["Address"]
column

0        Village Kodak, P.O- and P.S- Taliha, Upper Sub...
1                            Tili Lower Subansiri District
2        Amik Matai Society Post Box No 8 New Mekailian...
3        Rural works Division Daporijo Upper Subansiri ...
4            Basar, West Siang District Arunachal Pradesh.
                               ...
56179    FF-17, Shahu Steduim, Opposite HP Petrol pump,...
56180    Shop No. 3, R. R. Shukla Compound, Carter Road...
56181    Head Office:- Society for Integrated Developme...
56182    Vishwamitra N7k 38 bajarang colony cidco auran...
56183    SPARC, 2nd Floor, Marathi Municipal School Bui...
Name: Address, Length: 56184, dtype: object

In [85]:

# Nulls
print("Nulls:", sum(column.isnull()))
column = column.dropna()

# Emptry strings
print("Empty strings:", sum(column == " "))

# Lowercase all strings
column = column.str.lower()

# Unique values
print("No. of unique values:", len(column.unique()))

# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of Duplicates:", len(duplicates))

table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate regNo", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Nulls: 37
Empty strings: 0
No. of unique values: 55719
No. of Duplicates: 362

                                       Duplicate regNo  Count
0                                                  NaN     29
1    civil line-1, near rohit hotel, shri ram hospi...      8
2    hindi prachar sabha hyderabad sri ram hindi bh...      5
3      chanditala park, p.o-subashgram, p.s - sonarpur      4
4                              subash nagar, nizamabad      4
..                                                 ...    ...
357                 01, tiwari sadan professors colony      2
358  vill-baliadanga,p.o-baliadanga,p.s-kaliachak, ...      2
359                ward no 16 near ganesh maidan bidar      2
360  vill-bajeorancha, p.o.-sitakundu,p.s.-baruipur...      2
361                                            jalgaon      2

[362 rows x 2 columns]

# email

In [87]:
column = dataset["email"]
column

0                     atwsngo@yahoo.in
1                   aaws2011@gmail.com
2                  amikmatai@gmail.com
3                 allgumsing@gmail.com
4                    aneabow@gmail.com
                     ...
56179       seva_satara@rediffmail.com
56180             mailatsiit@gmail.com
56181    smita_kamlekar@rediffmail.com
56182           snehngo@rediffmail.com
56183             sparc@sparcindia.org
Name: email, Length: 56184, dtype: object

In [88]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 35
No. of unique values: 55999
No. of duplicates: 139

                    Duplicate Names  Count
0                               NaN     35
1    hindipracharsabhahyd@gmail.com      5
2        rahamathulla_ukd@yahoo.com      4
3                  ktmane@gmail.com      3
4             ngocon@rediffmail.com      3
..                              ...    ...
134     brds_society@rediffmail.com      2
135         gsm_world2002@yahoo.com      2
136              sai9bujji@yahoo.in      2
137     jayanti_mala@rediffmail.com      2
138         ritagramin311@gmail.com      2

[139 rows x 2 columns]

In [90]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
39516,http://www.indiangoslist.com/ngo-address/india...,INDIAN SOCIETY OF RURAL ANDURBAN DEVELOPMENTAN...,UP/2009/0006952,dr madan singh,sri chavi lal,smt neetu singh,sri birpal sachan,Registrar of Societies,Society,826/1997-98,...,Uttar Pradesh,0512-2285057,9.415145e+09,"L.I.G. 107,Barra-4, Kanpur (UP)",isrudar_knp27@yahoo.co.in,NaN,NaN,INDIAN SOCIETY OF RURAL ANDURBAN DEVELOPMENTAN...,This INDIAN SOCIETY OF RURAL ANDURBAN DEVELOPM...,special school for diabled persons. vocational...
39517,http://www.indiangoslist.com/ngo-address/india...,INDIAN SOCIETY OF RURAL AND URBAN DEVELOPMENT AND,UP/2009/0003465,Dr Madan Singh,Sri Chavi Lal,Smt Neetu Singh,Sri Birpal Sachan,Registrar of Societies,Society,"k-826/1997-98,",...,Uttar Pradesh,0512-2285057,9.415145e+09,"LIG-107, BARRA-4, KANPUR, UP-208027",isrudar_knp27@yahoo.co.in,NaN,NaN,INDIAN SOCIETY OF RURAL AND URBAN DEVELOPMENT ...,This INDIAN SOCIETY OF RURAL AND URBAN DEVELOP...,society is running a special school for disabl...

# Website

In [91]:
column = dataset["Website"]
column

0                              NaN
1                              NaN
2          http://ngo.india.gov.in
3                              NaN
4                              NaN
                   ...
56179                          NaN
56180                          NaN
56181                          NaN
56182           http://snehngo.org
56183    http://www.sparcindia.org
Name: Website, Length: 56184, dtype: object

In [92]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 44124
No. of unique values: 10903
No. of duplicates: 443

                   Duplicate Names  Count
0                              NaN  44124
1          http://ngo.india.gov.in    409
2      http://www.ngo.india.gov.in     73
3          http://www.facebook.com     38
4              http://ngo.india.in     31
..                             ...    ...
438      http://www.cmfchennai.com      2
439          http://www.intach.org      2
440    http://www.chestaangelin.in      2
441  http://www.herbalniamaths.com      2
442       http://www.snehalaya.org      2

[443 rows x 2 columns]

In [94]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
25781,http://www.indiangoslist.com/ngo-address/chaku...,CHAKULIA RURAL DEVELOPMENT SOCIETY,WB/2010/0035563,Md Shis Mortaz,Md Sirajul Islam,Md Shis Mortaz,Md Badir,Registrar of Societies,Society,S/1L/27366,...,West Bengal,03525-258160,9.614661e+09,Chakulia Rural Development Society At Milanpar...,crdsshis@gmail.com,http://cdoindia.org,NaN,CHAKULIA RURAL DEVELOPMENT SOCIETY is located ...,This CHAKULIA RURAL DEVELOPMENT SOCIETY NGO ch...,All kinds of Rural Development programs
26787,http://www.indiangoslist.com/ngo-address/charb...,CHARBABUPUR MAKTAB,WB/2010/0036129,Mojibur Rahman,Taleb Ali,Mojibur Rahman,Bhuon Ali,Registrar of Societies,Society,S/95706,...,West Bengal,03174-200304,9.641340e+09,Charbabupur,cmaktab@gmail.com,http://cdoindia.org,NaN,CHARBABUPUR MAKTAB is located in Malda West Be...,This CHARBABUPUR MAKTAB NGO charity is working...,SHG
28292,http://www.indiangoslist.com/ngo-address/daksh...,DAKSHIN DINAJPUR AGRICULTURE AND RURAL HEALTH ...,WB/2010/0036127,Krishna Rabidas,Subodh Chandra Mohonta,Krishna Rabidas,tresurer,Registrar of Societies,Society,S/1L/28296,...,West Bengal,03174-200304,9.434222e+09,Balurghat,ddarhdsociety@gmail.com,http://cdoindia.org,NaN,DAKSHIN DINAJPUR AGRICULTURE AND RURAL HEALTH ...,This DAKSHIN DINAJPUR AGRICULTURE AND RURAL HE...,SHG
36399,http://www.indiangoslist.com/ngo-address/heleg...,HELEGACHI BIPLABI SANGHA,WB/2010/0034251,Prodyut Mondal,Syamapada Chakroborty,Prodyut Mondal,Parimal Mondal,Registrar of Societies,Society,S/79946,...,West Bengal,03174-200304,9.733511e+09,"Helegachi, PO. Pairachali, PS. Falta, PIN Code...",hbsangha@gmail.com,http://cdoindia.org,NaN,HELEGACHI BIPLABI SANGHA is located in Klkata ...,This HELEGACHI BIPLABI SANGHA NGO charity is w...,Self help group Cultural Programs Games & Sports
40072,http://www.indiangoslist.com/ngo-address/madhy...,MADHYA RAMAKRISHNAPUR GRAMIN UNNAYAN SAMITY,WB/2010/0036122,Mizanur Rahaman,Sirajuddin Mondal,Mizanur Rahaman,Rejaul Mondal,Registrar of Societies,Society,S/87752,...,West Bengal,03174-200304,9.733385e+09,Sahapukur,mrgusamity@gmail.com,http://cdoindia.org,NaN,MADHYA RAMAKRISHNAPUR GRAMIN UNNAYAN SAMITY is...,This MADHYA RAMAKRISHNAPUR GRAMIN UNNAYAN SAMI...,shg

# Fax

In [95]:
column = dataset["Fax"]
column

0                 NaN
1                 NaN
2        03804-222878
3                 NaN
4                 NaN
             ...
56179    02162-230288
56180             NaN
56181    02344-247195
56182    0240-2481857
56183    022-23887566
Name: Fax, Length: 56184, dtype: object

In [96]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 44273
No. of unique values: 9446
No. of duplicates: 923

    Duplicate Names  Count
0               NaN  44273
1     mysql_prep(-)    910
2      0000-0000000     73
3       0000-000000     59
4      0522-3213944     37
..              ...    ...
918    01363-255217      2
919    04562-269238      2
920    02634-262591      2
921    079-23242323      2
922    011-41644077      2

[923 rows x 2 columns]

In [98]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
7160,http://www.indiangoslist.com/ngo-address/assoc...,ASSOCIATION OF SOCIAL REMEDIES AND MANAGEMENT,OR/2009/0021698,Achyutananda Nayak,Achyutananda Nayak,Ulupi Nayak,Satrughana Nayak,Registrar of Societies,Society,23018/26,...,Orissa,06784-251983,8.280259e+09,"At/Po: Charampa, Dist: Bhadrak-756101, Orissa",asram_achyuta@yahoo.com,http://ngo.india.gov.in,06784-250983,ASSOCIATION OF SOCIAL REMEDIES AND MANAGEMENT ...,NaN,Social Education Development women &Children e...
10010,http://www.indiangoslist.com/ngo-address/bishu...,BISHUNPURBINDHA WOMENS COOPERATIVE LTD,OR/2009/0021313,Golabun Bibi,Golabun Bibi,Tapaswini Das,Golabun Bibi,Registrar of Cooperative Societies,Cooperative Society,80,...,Orissa,06784-250983,NaN,At/Po: Bishnupurbindha Via: Arnapal Dist: Bhadrak,gulabun.bibi@gmail.com,http://ngo.india.gov.in,06784-250983,BISHUNPURBINDHA WOMENS COOPERATIVE LTD is loca...,This BISHUNPURBINDHA WOMENS COOPERATIVE LTD NG...,"To encourage thrift, self help and cooperation..."
30030,http://www.indiangoslist.com/ngo-address/natio...,NATIONAL ACTION FOR SOCIAL AND WEAKER AWARENESS,OR/2009/0016098,DILLIP NAYAK,SUDHAKAR DAS,DILLIP NAYAK,RATNAMANJARI NAYAK,Registrar of Societies,Society,1705-09,...,Orissa,06784-250977,9.937912e+09,"AT: SALANDI BY-PASS, PO:/DIST: BHADRAK, ORISSA...",naswa_ngo@rediffmail.com,http://ngo.india.gov.in,06784-250983,NATIONAL ACTION FOR SOCIAL AND WEAKER AWARENES...,This NATIONAL ACTION FOR SOCIAL AND WEAKER AWA...,"Ecologically sustainable, self-reliant society..."
30245,http://www.indiangoslist.com/ngo-address/neigh...,NEIGHBOUR,OR/2009/0017813,ABANI KUMAR PADHI,DR BAIDHAR SAHOO,ABANI KUMAR PADHI,BUDHIRAM JENA,Registrar of Societies,Society,21195/333,...,Orissa,06784-250217,9.438120e+09,ABANI KUMAR PADHI AT: BHABANIBINDHA PO: ICHHAP...,abanineighbour@yahoo.co.in,http://www.ngo.india.gov.in,06784-250983,NEIGHBOUR is located in BHADRAK Orissa . NEIGH...,This NEIGHBOUR NGO charity is working on Key I...,RELIEF MATERIALS PROVIDED TO AROUND 15 THOUSAN...
31602,http://www.indiangoslist.com/ngo-address/organ...,ORGANISATION FOR RURAL WOMEN AND AGRICULTURE D...,OR/2009/0018549,JAGATJYOTI PARHI,MILLAN SWAIN,JAGATJYOTI PARHI,SIVARAM MALLICK,Registrar of Societies,Society,BDK-1277-152,...,Orissa,06784-250983,9.040091e+09,"AT: KUNDIBAG, PO: BHADRAK, BY-PASS VIA: MADHAB...",orwad_ngo@rediffmail.com,http://ngo.india.gov.in,06784-250983,ORGANISATION FOR RURAL WOMEN AND AGRICULTURE D...,NaN,Main activities SHGs formation and Rural women...

#  Ngo Information

In [100]:
column = dataset["Ngo Information"]
column

0        ABO TANI WELFARE SOCIETY is located in Upper S...
1        AAN AAB WELFARE SOCIETY is located in Lower Su...
2        AMIK MATAI SOCIETY is located in Tezu Arunacha...
3        ALL HAMAI DEVELOPMENT ASSOCIATION AHDA is loca...
4        ANE ABO WELFARE SOCIETY is located in Arunacha...
                               ...
56179    SOCIETY FOR EMPOWERMENT OF VILLAGES AND AGRICU...
56180    SOCIETY FOR INSTITUTE OF INFORMATION TECHNOLOG...
56181    SOCIETY FOR INTEGRATD DEVELOPMENT AND RESEARCH...
56182    SOCIETY FOR NATIONALISM EDUCATION AND HEALTH A...
56183    SOCIETY FOR PROMOTION OF AREA RESOURCE CENTRES...
Name: Ngo Information, Length: 56184, dtype: object

In [101]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 0
No. of unique values: 55979
No. of duplicates: 51

                                      Duplicate Names  Count
0   is located in . is registered as a at of state...    152
1   HINDI PRACHAR SANGHA MUDHOL is located in HYDE...      5
2   HINDI PRACHAR SAMSAD is located in Hyderabad A...      3
3   NAVODAYA RURAL DEVELOPMENT SOCIETY is located ...      2
4   NAVJIVAN KHADI GRAMODHYOG SAMAJ SEVA TRUST is ...      2
5   NAVODIT GRAM UTTHAN MAHILA EVAM BAL VIKAS SAMI...      2
6   HUMAN RELIEF SOCIAL WELFARE SOCIETY is located...      2
7   KHANIKA RURAL DEVELOPMENT SOCIETY is located i...      2
8   LATE RAMPHAL SINGH HOON SALARPUR CHARITI TRUST...      2
9   NAVJIVAN VIDHALAYA SMITI is located in Sitapur...      2
10  PAROPKARAM KAROTI SEWA SAMITI is located in Lu...      2
11  ROOPAVAN is located in Kanpur Uttar Pradesh . ...      2
12  NAVJIVAN TRUST is located in HIMMATNAGAR Gujar...      2
13  NAVJIVAN SARVAJANIK SEVA MANDAL is located in ...      2
14  NAVJIVANVI KASMANDAL is located in adipur Guja...      2
15  NARAYANA VYAYAM SHALA VA KRIDA MANDAL is locat...      2
16  PAROPKAR EDUCATIONAL AND CULTURAL SOCIETY is l...      2
17  ROOPAYAN is located in RAJALIPATTY Tamil Nadu ...      2
18  NAVJIVAN TRUST is located in Bhavnagar Gujarat...      2
19  NAVJIVAN TRUST is located in Gujarat . NAVJIVA...      2
20  NAVJYOT KHADI GRAMODHYOG TRUST is located in A...      2
21  NAVJYOT FOUNDATION is located in Nadiad Gujara...      2
22  NAVJYOT KHADI GRAMUDHYOG TRUST is located in A...      2
23  NAVODAY EDUCATIONAL SOCIETY is located in limb...      2
24  NAVPRABHAT ANNABHUSATHE BAHUUDESHIYA SEVABHAVI...      2
25  ROHTASH MEMORIAL EDUCATIONAL SOCIETY is locate...      2
26  PARNIKA PRATISTHAN is located in Titilagarh Or...      2
27  PARSHURAM BAHINI is located in Bargarh Orissa ...      2
28  CCUBEZ is located in Assam . CCUBEZ is registe...      2
29  AGRANI MINORITY WELFARE SOCIETY is located in ...      2
30  ALHILAL ALPSANKHYAK SHIKSHAN PARSARAK WO SAMAJ...      2
31  NAVODAYA MAHILA SAMJAM is located in Raipur Ch...      2
32  NAVJIVINI SCHOOL is located in Patiala Punjab ...      2
33  HINDI PRACHAR SAMITI is located in Jaipur Raja...      2
34  ANJUMAN MADARSA IHYAULULOOM SAMITI is located ...      2
35  GHALIB ACADEMY is located in New Delhi Delhi ....      2
36  RISING GROUP is located in NAGAON Assam . RISI...      2
37  ROHANJI KOR BAHUUDDESHIYA SANSTHA is located i...      2
38  HINDI PRACHAR PARISHAD KAKCHING is located in ...      2
39  HINDI SAHITYA SAMMELAN PARIKSHA KENDER is loca...      2
40  HIND YUVA JAN KALYAN SAMITI is located in Delh...      2
41  PARSHVA FOUNDATION is located in Nagda jn Madh...      2
42  PARSHVA EDUCATION AND RESEARCH FOUNDATION SOCI...      2
43  KAHUARA MANAV KALYAN SANSTHAN is located in NA...      2
44  HINDECONRE SEARCHCENT RE is located in Chirmod...      2
45  NAVNIRMITI BAHUUDDESHIYA MAHILA MANDAL TULJAPU...      2
46  PAROPKARI SARVANGIN VIKAS SAMITI is located in...      2
47  PAROPKARI SARVANGIN VIKAS SAMITI is located in...      2
48  CHAUDHARY HARI PRASAD SINGH SHIKSHA PRASAR AVA...      2
49  RITA SEWA is located in Bihar . RITA SEWA is r...      2
50  RMEDS is located in PARBHANI Maharashtra . RME...      2

In [102]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
48319,http://www.indiangoslist.com/ngo-address/navji...,NAVJIVAN SARVAJANIK SEVA MANDAL,GJ/2010/0034014,Muljibhai Boghabhai Tundiya,Muljibhai Bogabhai Tundiya,Satishbhai Baldevdas Tundiya,Parghi Dahyabhai Talsibhai,Charity Commissioner,Trust,F/2250/Surendranagar,...,Gujarat,02759-235331,9.924686e+09,"At. Larkhadiya, Post. Sadad, Taluka. Lakhtar, ...",navjivanmandal@gmail.com,NaN,NaN,NAVJIVAN SARVAJANIK SEVA MANDAL is located in ...,This NAVJIVAN SARVAJANIK SEVA MANDAL NGO chari...,"Rural Development, Khadi Development, Women Em..."
48366,http://www.indiangoslist.com/ngo-address/navjy...,NAVJIVAN SARVAJANIK SEVA MANDAL,GJ/2010/0034014,Muljibhai Boghabhai Tundiya,Muljibhai Bogabhai Tundiya,Satishbhai Baldevdas Tundiya,Parghi Dahyabhai Talsibhai,Charity Commissioner,Trust,F/2250/Surendranagar,...,Gujarat,02759-235331,9.924686e+09,"At. Larkhadiya, Post. Sadad, Taluka. Lakhtar, ...",navjivanmandal@gmail.com,NaN,NaN,NAVJIVAN SARVAJANIK SEVA MANDAL is located in ...,This NAVJIVAN SARVAJANIK SEVA MANDAL NGO chari...,"Rural Development, Khadi Development, Women Em..."

# Key Issues

In [103]:
column = dataset["Ngo Information"]
column

0        ABO TANI WELFARE SOCIETY is located in Upper S...
1        AAN AAB WELFARE SOCIETY is located in Lower Su...
2        AMIK MATAI SOCIETY is located in Tezu Arunacha...
3        ALL HAMAI DEVELOPMENT ASSOCIATION AHDA is loca...
4        ANE ABO WELFARE SOCIETY is located in Arunacha...
                               ...
56179    SOCIETY FOR EMPOWERMENT OF VILLAGES AND AGRICU...
56180    SOCIETY FOR INSTITUTE OF INFORMATION TECHNOLOG...
56181    SOCIETY FOR INTEGRATD DEVELOPMENT AND RESEARCH...
56182    SOCIETY FOR NATIONALISM EDUCATION AND HEALTH A...
56183    SOCIETY FOR PROMOTION OF AREA RESOURCE CENTRES...
Name: Ngo Information, Length: 56184, dtype: object

In [104]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 0
No. of unique values: 55979
No. of duplicates: 51

                                      Duplicate Names  Count
0   is located in . is registered as a at of state...    152
1   HINDI PRACHAR SANGHA MUDHOL is located in HYDE...      5
2   HINDI PRACHAR SAMSAD is located in Hyderabad A...      3
3   NAVODAYA RURAL DEVELOPMENT SOCIETY is located ...      2
4   NAVJIVAN KHADI GRAMODHYOG SAMAJ SEVA TRUST is ...      2
5   NAVODIT GRAM UTTHAN MAHILA EVAM BAL VIKAS SAMI...      2
6   HUMAN RELIEF SOCIAL WELFARE SOCIETY is located...      2
7   KHANIKA RURAL DEVELOPMENT SOCIETY is located i...      2
8   LATE RAMPHAL SINGH HOON SALARPUR CHARITI TRUST...      2
9   NAVJIVAN VIDHALAYA SMITI is located in Sitapur...      2
10  PAROPKARAM KAROTI SEWA SAMITI is located in Lu...      2
11  ROOPAVAN is located in Kanpur Uttar Pradesh . ...      2
12  NAVJIVAN TRUST is located in HIMMATNAGAR Gujar...      2
13  NAVJIVAN SARVAJANIK SEVA MANDAL is located in ...      2
14  NAVJIVANVI KASMANDAL is located in adipur Guja...      2
15  NARAYANA VYAYAM SHALA VA KRIDA MANDAL is locat...      2
16  PAROPKAR EDUCATIONAL AND CULTURAL SOCIETY is l...      2
17  ROOPAYAN is located in RAJALIPATTY Tamil Nadu ...      2
18  NAVJIVAN TRUST is located in Bhavnagar Gujarat...      2
19  NAVJIVAN TRUST is located in Gujarat . NAVJIVA...      2
20  NAVJYOT KHADI GRAMODHYOG TRUST is located in A...      2
21  NAVJYOT FOUNDATION is located in Nadiad Gujara...      2
22  NAVJYOT KHADI GRAMUDHYOG TRUST is located in A...      2
23  NAVODAY EDUCATIONAL SOCIETY is located in limb...      2
24  NAVPRABHAT ANNABHUSATHE BAHUUDESHIYA SEVABHAVI...      2
25  ROHTASH MEMORIAL EDUCATIONAL SOCIETY is locate...      2
26  PARNIKA PRATISTHAN is located in Titilagarh Or...      2
27  PARSHURAM BAHINI is located in Bargarh Orissa ...      2
28  CCUBEZ is located in Assam . CCUBEZ is registe...      2
29  AGRANI MINORITY WELFARE SOCIETY is located in ...      2
30  ALHILAL ALPSANKHYAK SHIKSHAN PARSARAK WO SAMAJ...      2
31  NAVODAYA MAHILA SAMJAM is located in Raipur Ch...      2
32  NAVJIVINI SCHOOL is located in Patiala Punjab ...      2
33  HINDI PRACHAR SAMITI is located in Jaipur Raja...      2
34  ANJUMAN MADARSA IHYAULULOOM SAMITI is located ...      2
35  GHALIB ACADEMY is located in New Delhi Delhi ....      2
36  RISING GROUP is located in NAGAON Assam . RISI...      2
37  ROHANJI KOR BAHUUDDESHIYA SANSTHA is located i...      2
38  HINDI PRACHAR PARISHAD KAKCHING is located in ...      2
39  HINDI SAHITYA SAMMELAN PARIKSHA KENDER is loca...      2
40  HIND YUVA JAN KALYAN SAMITI is located in Delh...      2
41  PARSHVA FOUNDATION is located in Nagda jn Madh...      2
42  PARSHVA EDUCATION AND RESEARCH FOUNDATION SOCI...      2
43  KAHUARA MANAV KALYAN SANSTHAN is located in NA...      2
44  HINDECONRE SEARCHCENT RE is located in Chirmod...      2
45  NAVNIRMITI BAHUUDDESHIYA MAHILA MANDAL TULJAPU...      2
46  PAROPKARI SARVANGIN VIKAS SAMITI is located in...      2
47  PAROPKARI SARVANGIN VIKAS SAMITI is located in...      2
48  CHAUDHARY HARI PRASAD SINGH SHIKSHA PRASAR AVA...      2
49  RITA SEWA is located in Bihar . RITA SEWA is r...      2
50  RMEDS is located in PARBHANI Maharashtra . RME...      2

In [105]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
48319,http://www.indiangoslist.com/ngo-address/navji...,NAVJIVAN SARVAJANIK SEVA MANDAL,GJ/2010/0034014,Muljibhai Boghabhai Tundiya,Muljibhai Bogabhai Tundiya,Satishbhai Baldevdas Tundiya,Parghi Dahyabhai Talsibhai,Charity Commissioner,Trust,F/2250/Surendranagar,...,Gujarat,02759-235331,9.924686e+09,"At. Larkhadiya, Post. Sadad, Taluka. Lakhtar, ...",navjivanmandal@gmail.com,NaN,NaN,NAVJIVAN SARVAJANIK SEVA MANDAL is located in ...,This NAVJIVAN SARVAJANIK SEVA MANDAL NGO chari...,"Rural Development, Khadi Development, Women Em..."
48366,http://www.indiangoslist.com/ngo-address/navjy...,NAVJIVAN SARVAJANIK SEVA MANDAL,GJ/2010/0034014,Muljibhai Boghabhai Tundiya,Muljibhai Bogabhai Tundiya,Satishbhai Baldevdas Tundiya,Parghi Dahyabhai Talsibhai,Charity Commissioner,Trust,F/2250/Surendranagar,...,Gujarat,02759-235331,9.924686e+09,"At. Larkhadiya, Post. Sadad, Taluka. Lakhtar, ...",navjivanmandal@gmail.com,NaN,NaN,NAVJIVAN SARVAJANIK SEVA MANDAL is located in ...,This NAVJIVAN SARVAJANIK SEVA MANDAL NGO chari...,"Rural Development, Khadi Development, Women Em..."

# Major Activities and Achivements

In [106]:
column = dataset["Major Activities and Achivements"]
column

0        Flower Plantation, Weaving Material, Youth Dev...
1                                           Orphanage Home
2        Implemented the National Bamboo Mission progra...
3        Rural Development & Poverty Alleviation progra...
4        Maintenance and running of: (1) Treatment cum ...
                               ...
56179    Expertisatin in Micro Plainning & P.R.A. Follo...
56180    To open / run / manage institute / college of ...
56181    We would like to introduce about that the soci...
56182    our ngo is working in rural areas.we have all ...
56183    The Society for the Promotion of Area Resource...
Name: Major Activities and Achivements, Length: 56184, dtype: object

In [107]:

# Number of empty strings/missing values
print("Invalid:", sum(column == " ") + sum(column.isnull()))
print("No. of unique values:", len(column.unique()))
# Check for duplicates
counter = dict(Counter(column))
duplicates = { key:[value] for key, value in counter.items() if value > 1}
print("No. of duplicates:", len(duplicates))
table = pd.DataFrame.from_dict(duplicates)
table = table.melt(var_name="Duplicate Names", value_name="Count").sort_values(by=["Count"], ascending=False).reset_index(drop=True)
table

Invalid: 266
No. of unique values: 53477
No. of duplicates: 889

                                       Duplicate Names  Count
0                                                  NaN    266
1                               EDUCATION AND LITERACY     93
2    To guarantee elementary education to the poor ...     77
3                                            EDUCATION     57
4    Animal Husbandry, Dairying & Fisheries, Aged/E...     51
..                                                 ...    ...
884  1. CELEBRATION OF NATIONAL FESTIVALS :- To rem...      2
885                                     drinking water      2
886                                                  s      2
887  Implementation of Vocational Training, Rural a...      2
888  SYYED AHMAD SARWAJANIK WACHANALAY,PUSAD (REGD....      2

[889 rows x 2 columns]

In [108]:
dataset[column == table.iloc[13,0]].head()

,Url,NGO Name,Unique Id,Chief Functionary,Chairman,Secretary,Treasurer,Registered With,Type of NGO,Registration Number,...,State,Telephone,Mobile,Address,email,Website,Fax,Ngo Information,Key Issues,Major Activities and Achivements
2069,http://www.indiangoslist.com/ngo-address/cheyu...,CHEYUTA FOUNDATION,NL/2012/0054743,Namtan,Namtan,Kewisi,Namdikia,Registrar of Societies,Society,S.NO 3108,...,Nagaland,0370-2244562,9.402905e+09,"Chewang Society Administravive office, New Min...",n.namtan1945@gmail.com,NaN,NaN,CHEYUTA FOUNDATION is located in nagaland Naga...,This CHEYUTA FOUNDATION NGO charity is working...,.
3685,http://www.indiangoslist.com/ngo-address/banga...,BANGALORE BAPTIST HOSPITAL SOCIETY,KA/2010/0037209,Alexander Thomas,Alexander Thomas,Alexander Thomas,Alexander Thomas,Registrar of Societies,Society,"298,87-88 dt7.8.1987",...,Karnataka,080-22024700,9.448497e+09,Bangalore Baptist Hospital Bellary Road Hebbal,bbh@bbh.org.in,http://bbh.org.in,080-23437070,BANGALORE BAPTIST HOSPITAL SOCIETY is located ...,This BANGALORE BAPTIST HOSPITAL SOCIETY NGO ch...,.
5952,http://www.indiangoslist.com/ngo-address/hitas...,HITASHI JAN SEWA SANSTHAN,CG/2012/0053237,MADHORAM CHANDRAWANSHI,MADHORAM CHANDRAWANSHI,CHANDRA KUMAR SHRIVAS,BHUVAN CHANDRAWANSHI,Registrar of Societies,Society,1242,...,Chhattisgarh,0771-4095726,9.407781e+09,"VILLAGE: SAMANAPUR, TEH: KAWARDHA, DIST: KABIR...",purusottam2020@gmail.com,NaN,NaN,HITASHI JAN SEWA SANSTHAN is located in KAWARD...,This HITASHI JAN SEWA SANSTHAN NGO charity is ...,.
7574,http://www.indiangoslist.com/ngo-address/nav-j...,NAV JEEWAN NAV YUVAK MANDAL,CG/2012/0053327,SHEIKH MAHMOOD,SHEIKH MAHMOOD,AMBIKA SAHU,SACHCHA NAND THARUMAL,Registrar of Societies,Society,1962,...,Chhattisgarh,0771-4046325,9.993732e+09,"BEHIND DANDHU PARSAD, JULEKA MANZIL, K.K. ROAD...",purusottam1985@gmail.com,NaN,NaN,NAV JEEWAN NAV YUVAK MANDAL is located in RAIP...,This NAV JEEWAN NAV YUVAK MANDAL NGO charity i...,.
7989,http://www.indiangoslist.com/ngo-address/praya...,PRAYAS JAN SEWA SANSTHAN,CG/2012/0053319,SHIVDAYAL SAHU,SHIVDAYAL SAHU,NETRAPAL SAHU,KAILASH SHRIVAS,Registrar of Societies,Society,4055,...,Chhattisgarh,0771-4095726,9.893428e+09,"TAHSIL CHAWK, LORMI, DIST: MUNGELI PIN: 495334",purusottam2020@rediffmail.com,NaN,NaN,PRAYAS JAN SEWA SANSTHAN is located in MUNGELI...,This PRAYAS JAN SEWA SANSTHAN NGO charity is w...,.