# Schema

https://docs.google.com/document/d/1wDCb29oYVJIF2RPNtrnzxEYs1lH0J4RwYACDIn4kPhA/edit#heading=h.4wl6nl945n7g

In [1]:
import pandas as pd
import validators
import uuid
!ls

Untitled.ipynb   helpyourngo.sql  random.txt
helpyourngo.json lab1.ipynb

In [22]:
NgoBackground = pd.DataFrame(columns=[
    'ngoId', 
    'hasRegistration', 
    'hasFinance',
    'logo', 
    'yearEstablished', 
    'missionStatement', 
    'vision', 
    'objectives', 
    'legalStatus', 
    'areasOfOperation', 
    'activeStatus'
])
NgoRegistration = pd.DataFrame(columns=[
    'ngoId',
    'isRegistrationFor',
    'ngoType',
    'regNo',
    'regDate',
    'registrar',
    '12ANo',
    '12ARegdate',
    '12AUpload',
    '80GNo',
    '80GRegdate',
    '80GUpload',
    '35ACNo',
    '35ACRegdate',
    '35ACUpload',
    'fCRANo',
    'fCRARegdate',
    'natureListed',
    'fCRAStatus',
    'fCRAExpiration',
    'fCRAUpload',
    'pan',
    'tan',
    'gst',
    'notes'
])

NgoContact = pd.DataFrame(columns=[
    'ngoId',
    'ngoName',
    'orgEmail',
    'officePhone',
    'primaryPoc',
    'primaryPocPhone',
    'secondaryPoc',
    'secondaryPocPhone',
    'mailingAddress',
    'physicalAddress',
    'fieldOffices',
    'orgType',
    'orgWebsite',
    'websiteIsValid',
    'facebook',
    'twitter',
    'iInstagram',
    'youtube',
    'whatsapp',
    'otherSocials',
    'scrapeSource',
    'executiveDirector',
    'technicalSupport',
    'chairmanName',
    'chairmanMobile',
    'chairmanEmail',
    'viceChairmanName',
    'viceChairmanMobile',
    'viceChairmanEmail',
    'secretaryName',
    'secretaryMobile',
    'secretaryEmail',
    'assistantSecretaryName',
    'assistantSecretaryMobile',
    'assistantSecretaryEmail'
])

NgoFinance = pd.DataFrame(columns=[
    'ngoId',
    'fiscalYear',
    'totalIncome',
    'totalGrant',
    'totalExpense',
    'totalAssets',
    'totalLiabilities',
    'totalFundingGap',
    'sourceOfFunds',
    'majorFunders',
    'ngoBudgetAllocation',
    'ngoBudgetUtilization',
    'auditReport',
    'avgMonthlyExpenditure',
    'avgMonthlyOverhead',
    'longTermLoan',
    'fulltimeEmployees',
    'parttimeEmployees',
    'employmentExpenses',
    'fulltimeVolunteers',
    'parttimeVolunteers',
    'volunteerExpenses',
    'consultants',
    'consultantExpenses',
    'occupancyExpenses',
    'fundraisingExpenses'
])

In [23]:
df = pd.read_json("helpyourngo.json")
df["name"] = df["name"].str.title()
df = df.dropna(subset=['name'])
df["ngoId"] = [uuid.uuid3(uuid.NAMESPACE_URL, _) for _ in df["name"]]
df.head()

,name,last_updated,address,mobile,email,website,annual_expenditure,description,ngoId
0,Aai Caretaker,2020.0,"Room No. B/4, Ashok Nagar, Near Kris...",+91 22 25530537,info@aaicaretaker.org.in,www.aaicaretaker.in,"138,990,084",Aai Caretaker is involved in diverse...,608f2a51-35a5-3002-8229-c078531a7cdd
1,Aakriti,2015.0,"J-159, Sector-10 DLF, Faridabad 1210...",+91 9312263021,aakritischool@yahoo.in,www.aakritingo.org,"1,023,204","A parent-initiative, Association for...",c894bc4b-4c34-38ca-a874-fa9f9bc69677
2,Aakash Maindwal Foundation,2016.0,"107, First Floor, Block - Milano, Ma...",+91 120 4377527,aakashmaindwalfoundation@gmail.com,www.amfindia.org,"767,980",Aakash Maindwal Foundation has been ...,b023c29c-3ae0-3128-881c-b0245892e0aa
3,Aaradhana Sanstha,2013.0,"14, Sulabhpuram, Sikandara Bodla Roa...",+91 9639161612,drhchaudhary@yahoo.com,None,None,Aaradhana Sanstha was formed for edu...,7c8e8ac2-e381-3a90-bf13-c3786b890a05
4,Action Against Hunger (Fight Hunger ...,2019.0,"201, Sai Prasad Building, Sion Kamga...",+91 022 2611 1275,contact@fighthungerfoundation.org,www.actionagainsthunger.in,"86,348,954",Action Against Hunger (AAH) register...,3e5c857a-4e60-36d9-b3a3-d14c02bf373b

In [24]:
df.columns

Index(['name', 'last_updated', 'address', 'mobile', 'email', 'website',
       'annual_expenditure', 'description', 'ngoId'],
      dtype='object')

In [25]:
# Set display option to show full text
pd.set_option('display.max_colwidth', 40)
print(df.description[:1])

0    Aai Caretaker is involved in diverse...
Name: description, dtype: object

In [33]:
# Mapping for NgoContact
NgoContact["ngoId"] = df['ngoId']
NgoContact["ngoName"] = df["name"].str.title()
NgoContact["orgEmail"] = df["email"]
NgoContact["officePhone"] = df["mobile"]
NgoContact["physicalAddress"] = df["address"]
NgoContact["orgWebsite"] = df["website"]

def validate_url(url):
    if pd.isna(url):  # handle NaN values
        return False
    if validators.url(url):
        return True
    else:
        return False

NgoContact['websiteIsValid'] = NgoContact['orgWebsite'].apply(validate_url)
NgoContact['scrapeSource'] = 'helpyourngo'

# Mapping for NgoFinance
NgoFinance["ngoId"] = df['ngoId']
NgoFinance["fiscalYear"] = df['last_updated'].astype(int)
NgoFinance['totalExpense'] = df['annual_expenditure']
#NgoFinance['avgMonthlyExpenditure'] = df['annual_expenditure']/12

# Mapping for NgoBackground
NgoBackground["ngoId"] = df['ngoId']
NgoBackground["objectives"] = df["description"]

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [32]:
NgoFinance

,ngoId,fiscalYear,totalIncome,totalGrant,totalExpense,totalAssets,totalLiabilities,totalFundingGap,sourceOfFunds,majorFunders,...,fulltimeEmployees,parttimeEmployees,employmentExpenses,fulltimeVolunteers,parttimeVolunteers,volunteerExpenses,consultants,consultantExpenses,occupancyExpenses,fundraisingExpenses
0,608f2a51-35a5-3002-8229-c078531a7cdd,2020.0,NaN,NaN,"138,990,084",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,c894bc4b-4c34-38ca-a874-fa9f9bc69677,2015.0,NaN,NaN,"1,023,204",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,b023c29c-3ae0-3128-881c-b0245892e0aa,2016.0,NaN,NaN,"767,980",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7c8e8ac2-e381-3a90-bf13-c3786b890a05,2013.0,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3e5c857a-4e60-36d9-b3a3-d14c02bf373b,2019.0,NaN,NaN,"86,348,954",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
683,ad3c358b-78d3-3f35-9d8d-0e97a1289d66,2020.0,NaN,NaN,"903,612",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
684,fcc289bc-24ea-32b6-9853-9d1bbd7ec893,2015.0,NaN,NaN,"7,907,718",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
685,1dcb89b0-98e3-39ea-9511-c474d4dbeabf,2015.0,NaN,NaN,"9,493,108",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
686,9054faca-dec0-3e34-be0c-0924cb30a75f,2014.0,NaN,NaN,"2,473,686",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
687,a6fbde2a-e4f2-340f-87d6-30725e0a9e4a,2014.0,NaN,NaN,"4,558,280",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Drop rows where all columns are empty except Id
NgoContact = NgoContact.dropna(how='all', subset=NgoContact.columns.difference(['ngoId']))
NgoRegistration = NgoRegistration.dropna(how='all', subset=NgoRegistration.columns.difference(['ngoId']))
NgoFinance = NgoFinance.dropna(how='all', subset=NgoRegistration.columns.difference(['ngoId']))

KeyError: ['12ANo', '12ARegdate', '12AUpload', '35ACNo', '35ACRegdate', '35ACUpload', '80GNo', '80GRegdate', '80GUpload', 'fCRAExpiration', 'fCRANo', 'fCRARegdate', 'fCRAStatus', 'fCRAUpload', 'gst', 'isRegistrationFor', 'natureListed', 'ngoType', 'notes', 'pan', 'regDate', 'regNo', 'registrar', 'tan']